### ISSUE TITLE
q3bsp lightmap no longer bound to light style

### ISSUE THREAD

**Issue by hemebond** [DarkPlacesEngine/darkplaces#100]
Nahuel has discovered that in 2018 versions of DarkPlaces and beyond, the lightmap on q3bsp maps is not bound to a light style, which means it can't be manipulated, and also breaks the dpmod _darkmode_ gameplay mode. It is also used by Wrath to simulate lightning.

DarkMod darkmode in 2017 build:
![image](https://github.com/DarkPlacesEngine/darkplaces/assets/424218/b712632d-304b-4940-a9bf-5b8648402399)

Darkmod darkmode in 2018 build:
![image](https://github.com/DarkPlacesEngine/darkplaces/assets/424218/40451b96-94f9-4327-804d-fd22626b822b)

Tested and confirmed to still be an issue in the latest master/main.

**Comment by Baker7** [comment]
Hemebond, can you provide the last known working version of DarkPlaces that did not have the issue.

I assume Wrath doesn't have issue?  Is this correct?

If you can tell me the most recent one where it worked, I would like to take a look at this.

**Comment by hemebond** [comment]
> Hemebond, can you provide the last known working version of DarkPlaces that did not have the issue.

I tried to compile older versions to find and test the exact commit but couldn't compile (I need to try with https://github.com/DarkPlacesEngine/darkplaces/commit/5e9e998). It appears there were significant light style changes in https://github.com/DarkPlacesEngine/darkplaces/commit/fb21704.

> I assume Wrath doesn't have issue? Is this correct?

Correct. Wrath is based on a much older version.

> If you can tell me the most recent one where it worked, I would like to take a look at this.

The most recent "release" that works is 2017-08-30.

**Comment by Baker7** [comment]
This is highly likely part of the solution:

Classic DarkPlaces does this in gl_rmain.c in R_GetCurrentTexture:

			VectorSet(t->dlightcolor, t->lightmapcolor[0] * t->lightmapcolor[3], t->lightmapcolor[1] * t->lightmapcolor[3], t->lightmapcolor[2] * t->lightmapcolor[3]);
			colorscale = 2;
			// q3bsp has no lightmap updates, so the lightstylevalue that
			// would normally be baked into the lightmap must be
			// applied to the color
			// FIXME: r_glsl 1 rendering doesn't support overbright lightstyles with this (the default light style is not overbright)
			if (model->type == mod_brushq3)
				colorscale *= r_refdef.scene.rtlightstylevalue[0];
			colorscale *= r_refdef.lightmapintensity;
			VectorScale(t->lightmapcolor, r_refdef.scene.ambient, ambientcolor);
			VectorScale(t->lightmapcolor, colorscale, t->lightmapcolor);

**Comment by Baker7** [comment]
Solution:

gl_rmain.c , R_UpdateVariables

	if (r_refdef.scene.worldmodel)
	{
		r_refdef.scene.lightmapintensity *= 
			r_refdef.scene.worldmodel->lightmapscale;
			// Baker: Add this ...
		if (cl.worldmodel && cl.worldmodel->type == mod_brushq3) {
			r_refdef.scene.lightmapintensity *= r_refdef.scene.rtlightstylevalue[0];
		}
	}
