### ISSUE TITLE
Current beta - gamedir change corrupts cvars

### ISSUE THREAD

**Issue by Baker7** [DarkPlacesEngine/darkplaces#101]
**This relates to attempts to build on Windows with current darkplaces master.  As I understand it, building on Windows is not really supported at this time.  And I knew that going in ...**

Current beta - gamedir change corrupts cvars.

If I type "gamedir undergate", the menu_progs cvar is reset to "default" which is corrupted data.

I built current DarkPlaces beta using Visual Studio 2022 and this is running on Windows 10 with a GeForce GTX 960M.
.
.
.
.

Since this is not the preferred method to build, this could be my fault for several different reasons including that the .vcxproj  seemed to be out of date and I had to mess with it some, it could be missing option or compiler flags.

`void Cvar_RestoreInitState(cvar_state_t *cvars)
`if (c->defstring)
`	Z_Free((char *)c->defstring);
`	c->defstring = Mem_strdup(zonemempool, c->initstate->defstring);
`	if (c->string)
`		Z_Free((char *)c->string);
`	c->string = Mem_strdup(zonemempool, c->initstate->string);`

(The documented msys2 method to compile on Windows works, but the .exe will not start and has the message "Application failed to start" ... I expect I can get it to produce a functional .exe with some messing around.)

**Comment by Baker7** [comment]
I am suspecting a project setup issue in Visual Studio somewhere.

I'll see what mingw does.

**Comment by hemebond** [comment]
> Are there instructions on how to compile a Windows .exe on Linux?

I think you can do the following:
```bash
make DP_MAKE_TARGET=mingw sdl-release
```

**Comment by Baker7** [comment]
I managed to build DarkPlaces master from this version:

https://github.com/DarkPlacesEngine/darkplaces/tree/9fe4c204bf70b62ce92a7c2114414a16e80b974b

Using mingw64 and it does not have issues so far on gamedir change.

I wired CodeBlocks to use the MSYS2 MinGW64 provided compiler instead of CodeBlocks provided MinGW64 compiler.

Although a compile in MSYS2 MinGW64 does make a .exe that does not run (just providing information), with some reordering of linker parameters I made one that does run.

So the MinGW64 compiler that comes with CodeBlocks 20.03 is different enough from the MSYS2 MinGW64 compiler that it matters.

**Comment by Baker7** [comment]
I've tried a number of different ways to make a functioning a windows .exe from DarkPlaces master and the DarkPlaces apr 19 version.

Some methods do make an .exe that runs, all of them get some sort of memory corruption on gamedir change.

I've used many methods, the MSYS2 method, etc.

I can make a Linux binary that functions just fine.

**Comment by Baker7** [comment]
Here at least is a partial fix ..

In Cvar_RestoreInitState, c->initstate is a memory copy of the cvar struct.

c->initstate->string is not a copy of the string, it is pointer to the same string.

Cvar_RestoreInitState is freeing the original string (c->string) and then allocating a copy from c->initstate->string --- which is the same freed string as c->string.

This partial fix addresses the above.

				Con_DPrintf("Cvar_RestoreInitState: Restoring cvar \"%s\"\n", c->name);
				const char *s_copy_str = NULL;
				const char *s_copy_defstr = NULL;
				
				if (c->string)		s_copy_str = Mem_strdup(zonemempool, c->initstate->string);
				if (c->defstring)	s_copy_defstr = Mem_strdup(zonemempool, c->initstate->defstring);
				if (c->defstring)
					Z_Free((char*)c->defstring);
				c->defstring = s_copy_defstr;//   Mem_strdup(zonemempool, c->initstate->defstring);
				if (c->string)
					Z_Free((char*)c->string);
				c->string = s_copy_str; // Mem_strdup(zonemempool, c->initstate->string);
			}
			c->flags = c->initstate->flags;
			c->value = c->initstate->value;
			c->integer = c->initstate->integer;
			VectorCopy(c->initstate->vector, c->vector);
			cp = &c->next;

**Comment by Baker7** [comment]
> updating c->initstate->string / c->initstate->defstring to c->string / c->defstring after the mem_strdup might fix because those are stale.

There is still something else going on.

cvars->hashtable issue with null pointer to cvar on 2nd gamedir change.

**Comment by Baker7** [comment]
for (cp2 = &cvars->hashtable[hashindex]->cvar; (c2 = *cp2); )
			{
				if (c2 == c) {
					if (cvars->hashtable[hashindex]->next)
						*cp2 = cvars->hashtable[hashindex]->next->cvar;
					else cvars->hashtable[hashindex] = NULL; // Baker: there is no next ..
					break;
				}
				else
					cp2 = &cvars->hashtable[hashindex]->next->cvar;
			}

Part 2

		if (c->initstate)
		{
			// restore this cvar, it existed at init
			if (((c->flags ^ c->initstate->flags) & CF_MAXFLAGSVAL)
				|| strcmp(c->defstring ? c->defstring : "", c->initstate->defstring ? c->initstate->defstring : "")
				|| strcmp(c->string ? c->string : "", c->initstate->string ? c->initstate->string : ""))
			{
				Con_DPrintf("Cvar_RestoreInitState: Restoring cvar \"%s\"\n", c->name);
				const char *s_copy_str = NULL;
				const char *s_copy_defstr = NULL;
				
				if (c->string)		s_copy_str = Mem_strdup(zonemempool, c->initstate->string);
				if (c->defstring)	s_copy_defstr = Mem_strdup(zonemempool, c->initstate->defstring);
				if (c->defstring)
					Z_Free((char*)c->defstring);
				c->defstring = c->initstate->defstring = s_copy_defstr;//   Mem_strdup(zonemempool, c->initstate->defstring);
				if (c->string)
					Z_Free((char*)c->string);
				c->string =  c->initstate->string = s_copy_str; // Mem_strdup(zonemempool, c->initstate->string);

			}

After both adjustments, we seem to survive unlimited gamedir changes.

Needs more testing.

**Comment by Cloudwalk9** [comment]
Building on Windows is supported. I just haven't bothered writing the instructions for Visual Studio in the README yet.

**Comment by Baker7** [comment]
Hey Cloudwalk, thanks for the reply.   Kleshby wrote a tutorial which is pretty good and walks through the NuGet / SDL2.

https://quake.by/tutorials/?id=52

**Comment by Baker7** [comment]
Visual Studio 2022 hates the pre-existing freetype-6.dll for Windows and throws an exception in debug with ntdll.dll.

The following freetype.dll made by the FreeType project in Visual Studio does not throw an exception:

https://github.com/ubawurinna/freetype-windows-binaries/tree/master/release%20dll/win64

**Comment by bones-was-here** [comment]
I rewrote much of the cvar state restoration and fixed old gamedir bugs in 32c99c7b0a58545b273fa713d81d6bbfb3b8ebe6 5db369bea3d0cdd3dbd3b5b8038a399f0dbf84b6 7b7009740d891a5454c39106459ec9c63b74aa10 so it should be reliable in all supported games now.

The best maintained way to build for Windows is MinGW because that's what Xonotic uses, and because unlike Microsoft, GCC supports current C standards.  You can find x86_64 binaries including DLLs in the engine zip at https://beta.xonotic.org/autobuild/ which are all cross compiled using MinGW and updated when commits are pushed to master.
