### ISSUE TITLE
Q1 Sky After The First Never Loads

### ISSUE THREAD

**Issue by Baker7** [DarkPlacesEngine/darkplaces#105]
Unless I am messing something up, no Quake sky ever loads after the first if the tex

	// if already loaded just return it, otherwise make a new skinframe
	skinframe = R_SkinFrame_Find(name, textureflags, comparewidth, compareheight, comparecrc, true);
	if (skinframe->base)
		return skinframe;

Every map after the first one, it will find skinframe for the sky texture and never load a Q1 sky again.

Example: E1M1 is supposed to have a blues sky.  In DarkPlaces Beta, it will usually have a purple sky because the first map loaded with E1M3 (demo1.dem which has purple sky) or START (purple sky).

vid_restart does fix.

The reason this issue occurs is the internal texture name is "sky_solidtexture" and after the first map this will be found 100% of the time, so the texture upload never occurs.

(This may lead to a different type of issue.   Quake .bsp 2 different maps might use the same texture name but they are not the same texture.  This was a problem in a few places even for id1 maps!)

**Comment by hemebond** [comment]
#58

**Comment by Baker7** [comment]
Ah, I didn't see that issue -- my bad.

**Comment by Baker7** [comment]
Solution:
	loadmodel->brush.solidskyskinframe = R_SkinFrame_LoadInternalBGRA("sky_solidtexture", 0         , (unsigned char *) solidpixels, w, h, 0, 0, 0, vid.sRGB3D, true);
	loadmodel->brush.alphaskyskinframe = R_SkinFrame_LoadInternalBGRA("sky_alphatexture", TEXF_ALPHA, (unsigned char *) alphapixels, w, h, 0, 0, 0, vid.sRGB3D, true);

Extra field for R_SkinFrame_LoadInternal qbool is_q1skyload, only above is it set to true.

skinframe_t *R_SkinFrame_LoadInternalBGRA(const char *name, int textureflags, 
	const unsigned char *skindata, int width, int height, int comparewidth, 
	int compareheight, int comparecrc, qbool sRGB, qbool is_q1skyload)
{
	int i;
	skinframe_t *skinframe;
	char vabuf[1024];

	if (cls.state == ca_dedicated)
		return NULL;

	// if already loaded just return it, otherwise make a new skinframe
	skinframe = R_SkinFrame_Find(name, textureflags, comparewidth, compareheight, comparecrc, true);

	if (skinframe->base) {
		if (is_q1skyload) {
			R_SkinFrame_PurgeSkinFrame(skinframe);
		} else {
			return skinframe;
		}
	}

**Comment by hemebond** [comment]
Perhaps I implemented it incorrectly, but this didn't seem to work for my quakemash map. I'll test again later with a smaller test map.
