### ISSUE TITLE
DarkPlaces Misses Keyups and Why + Fix

### ISSUE THREAD

**Issue by Baker7** [DarkPlacesEngine/darkplaces#106]
DarkPlaces Beta misses keyups.  One time, I had stuck keys simply due to low fps.  Once done reading this, it will make perfect sense why that could happen ...

Old DarkPlaces code in Zircon in keys.c Key_Event goes like this:

			// ignore key repeats on binds and only send the bind if the event hasnt been already processed by csqc
			if (!q && bind)
			{
				if (keydown[key] == 1 && down)
				{
					// First key down
					// button commands add keynum as a parm
					if (bind[0] == '+')
						Cbuf_AddTextLine (va(vabuf, sizeof(vabuf), "%s %d", bind, key));
					else
					{
						Cbuf_AddTextLine (bind);
					}
				} else if (bind[0] == '+' && !down && keydown[key] == 0) {
					// Key up
					Cbuf_AddTextLine (va(vabuf, sizeof(vabuf), "-%s %d", bind + 1, key));
				}
			}

DarkPlaces Beta ...

			// ignore key repeats on binds and only send the bind if the event hasnt been already processed by csqc
			if (!q && bind)
			{
				if (keydown[key] == 1 && down)
				{
					// First key down
					// button commands add keynum as a parm
					if (bind[0] == '+')
						Cbuf_InsertText(cmd, va(vabuf, sizeof(vabuf), "%s %d" NEWLINE, bind, key));
					else
						Cbuf_InsertText(cmd, va(vabuf, sizeof(vabuf), "%s" NEWLINE, bind));
				}
				else if (bind[0] == '+' && !down && keydown[key] == 0) {
					// Key up
					Cbuf_InsertText(cmd, va(vabuf, sizeof(vabuf), "-%s %d" NEWLINE, bind + 1, key));
				}
			}

Seems fine, right?   Well ... no ...

InsertText puts it at the start of the buffer.

AddText puts it at the end.

If I get low fps or it's intermission, AddText queues it like this ...

queue:
+forward
-forward
+forward
-forward

But InsertText ...

Key is down ...

queue:
+forward

Key is up

queue:
-forward
+forward

So you get the events in reverse, and the -forward is ignored.  And then you get stuck with the +forward.

And since no key is down anymore, there is no key up event and the next keydown doesn't match what input thinks.

**Comment by bones-was-here** [comment]
Good catch, I can reproduce this, my bad.
