### ISSUE TITLE
Ctrl + Plus not working

### ISSUE THREAD

**Issue by Baker7** [DarkPlacesEngine/darkplaces#110]
In DarkPlaces Beta, CTRL plus '+' is supposed to enlarge the console font.  It doesn't work.  In keys.c it is checking for '+'.  You can't receive that as a scancode, the key is '=' and it is '+' when you hold shift.  So anyway, easy fix.

**Comment by hemebond** [comment]
I changed the code like this:
```patch
diff --git a/keys.c b/keys.c
index a3a6d926..de0d310b 100644
--- a/keys.c
+++ b/keys.c
@@ -1265,7 +1265,7 @@ static void Key_Console(cmd_state_t *cmd, int key, int unicode)
        if (keydown[K_CTRL])
        {
                // text zoom in
-               if ((key == '+' || key == K_KP_PLUS) && KM_CTRL)
+               if ((key == '=' || key == K_KP_PLUS) && KM_CTRL)
                {
                        if (con_textsize.integer < 128)
                                Cvar_SetValueQuick(&con_textsize, con_textsize.integer + 1);
```
And the keypad `+` stopped working. It looks like maybe the `K_KP_PLUS` isn't actually working.

**Comment by terencehill** [comment]
Here (Windows 10) ctrl + works as expected. ctrl K_KP_PLUS works too regardless of numlock state.

I think there could be something wrong with your keyboard or your OS.

**Comment by hemebond** [comment]
> Here (Windows 10) ctrl + works as expected. ctrl K_KP_PLUS works too regardless of numlock state.
> 
> I think there could be something wrong with your keyboard or your OS.

Key keypad returns the ASCII code for `+`, `-`, and `0` (zero). I'm not sure what the `K_KP_*` codes are based on (they are listed in `keycodes.qc`)

**Comment by terencehill** [comment]
Oh, US/UK keyboard layout doesn't have direct access to the plus sign, `shift =` types the plus sign.

In my italian keyboard I have a plus key that I can use directlyб otoh I don't have direct access to =, I have to press shift 0.

Perhaps the best solution is to accept `ctrl =` too as a shortcut to increase font size without removing `ctrl +`

**Comment by hemebond** [comment]
> Perhaps the best solution is to accept `ctrl =` too as a shortcut to increase font size without removing `ctrl +`

Yeah, that's what I've done in the pull request. Works fine on both sets of -+ now.
