### ISSUE TITLE
I want new "GIVE A" cheat command

### ISSUE THREAD

**Issue by ghost** [DarkPlacesEngine/darkplaces#132]
As how the "GIVE H" cheat command is used to set player's health to any number the cheater wants, the "GIVE A" cheat command is used to set player's armor to any number the cheater wants.

**Comment by hemebond** [comment]
I believe this is usually controlled by the mod/game code (QuakeC), not the engine.

**Comment by Baker7** [comment]
No give "h" is done in the engine.  Zircon has give "a" for armor and has for over a year.  Quakespasm and other engines all support give "a".

**Comment by Baker7** [comment]
Giving yourself armor is nice, but probably not really necessary.  I am kind of defending fteqw a little because fteqw Spike/Shoipke is one of the most helpful people on the face of the planet.  He helped me tons of times in earlier days.

**Comment by FeatureRequestor** [comment]
> Giving yourself armor is nice, but probably not really necessary. I am kind of defending fteqw a little because fteqw Spike/Shoipke is one of the most helpful people on the face of the planet. He helped me tons of times in earlier days.

Nobody bothered even to tell me this but you are right, Spike indeed did excellent work.

**Comment by hemebond** [comment]
> I asked this "GIVE A" cheat command also for fteqw but nobody wanted to do it and I always wondered why if the task is just a few lines of code as you say.

What if the game doesn't have armour? What if the armour behaviour is different to Quake?

**Comment by bones-was-here** [comment]
> I always wondered why if the task is just a few lines of code as you say

Because none of the people who want it bothered even to open a PR

**Comment by FeatureRequestor** [comment]
> > I asked this "GIVE A" cheat command also for fteqw but nobody wanted to do it and I always wondered why if the task is just a few lines of code as you say.
> 
> What if the game doesn't have armour? What if the armour behaviour is different to Quake?

I expect the "GIVE A" cheat command to be recognized on quake games, not on games are not quake but now that I am thinking on it this feature request is really redundant.

**Comment by FeatureRequestor** [comment]
> I believe this is usually controlled by the mod/game code (QuakeC), not the engine.

Is the "GIVE H" cheat command also controlled by the mod/game code (QuakeC) too?

I tried to find the implementation of the "GIVE H" cheat command anywhere in the QuakeC source code of the game and didn't find it anywhere.

**Comment by hemebond** [comment]
> > I believe this is usually controlled by the mod/game code (QuakeC), not the engine.
> 
> Is the "GIVE H" cheat command also controlled by the mod/game code (QuakeC) too?

No, in this case it is actually implemented in the engine. I had forgotten about it, and it works on ammo and weapons too. If you use `give health` by itself the game doesn't realise you're dead so you can actually still look around and shoot.
