### ISSUE TITLE
I want to know the remaining times of air and powerups like quad damage, pentagram of protection, ring of shadows and bio suit

### ISSUE THREAD

**Issue by ghost** [DarkPlacesEngine/darkplaces#134]
When underwater the player has about 12 seconds until he is drown but the information when this will happen is hidden.

This is also true for all the powerups like quad damage (that multiplies inflict damage by 4), pentagram of protection (that makes player invulnerable), ring of shadows (that makes player invisible) and bio suit (that allows player to breathe underwater).

They all last about 30 seconds but the information about when each is expired is hidden too.

I would like to always know when something happens by drawing text, number or bar showing the remaining time until it happens.

I would also like to have it done in the C/C++ level rather than in the QuakeC level.

I will try to do it myself and I will leave this issue open for anyone who is interested in and accepts this challenge.

**Comment by hemebond** [comment]
This is handled by game code (QuakeC), not the engine. What is the engine to do if the game does not have one or more of those items?

**Comment by bones-was-here** [comment]
If you do this in the engine it would be a fragile hack and would break as soon as the gamecode uses a different edict number or field name.

**Comment by bones-was-here** [comment]
That said, id1 Quake lacks CSQC so to implement it there would require an engine patch, but it would not be expected to work in anything different from id1 Quake.  I'll leave it open in case LH wants to comment as to whether something like this would be acceptable, but I expect it will just sit open forever.

**Comment by FeatureRequestor** [comment]
I thought that anything that is possible on QuakeC (SSQC + CSQC) should be also possible in C/C++.

QuakeC was written in C/C++, no?

**Comment by bones-was-here** [comment]
The language isn't relevant.  Gameplay features are handled by gamecode, the engine provides gamecode with APIs it needs to implement game-specific features, in this case a HUD panel.  The original id1 Quake is an exception to the rule in that its HUD is implemented in the engine, which isn't the right place for it but like many commercial games it was rushed out to meet a deadline and get paid.  In Q3 they moved the HUD into gamecode, DP supports this via CSQC.

**Comment by FeatureRequestor** [comment]
I understand. Thanks.

**Comment by hemebond** [comment]
> I'll leave it open in case LH wants to comment as to whether something like this would be acceptable, but I expect it will just sit open forever.

@ladyhavoc do you have an opinion on this? If not I think we should go ahead and close it.

**Comment by ladyhavoc** [comment]
Changing the HUD is beyond the scope of the engine - that is a job for CSQC to do if it is desired in a mod.

Displaying timers is often considered a cheat by pro players, with many pro-player focused mods deliberately omitting any countdown timers and leaving it to player skill to keep track of everything, so it shouldn't be part of the engine even if it is feasible to do so, the mod dictates what the HUD is.
