### ISSUE TITLE
I don't see an option to make darkplaces.exe for windows

### ISSUE THREAD

**Issue by ghost** [DarkPlacesEngine/darkplaces#139]
I have followed all the Windows (MSYS2) instructions since Visual Studio no longer builds darkplaces successfully and I have made a Linux binary of darkplaces but not windows binary but I want to make windows binary of darkplaces, not linux binary.

I entered `make help` but I don't see any option to make windows binary.
All options seem to make linux binaries only.

Did I miss something?

**Comment by bones-was-here** [comment]
When you do `make sdl-release` it compiles the platform-specific binary, so in mingw `darkplaces-sdl.exe` should be created.  
I updated the README.md so hopefully it's clearer.
