### ISSUE TITLE
Sounds under water should be muffled

### ISSUE THREAD

**Issue by hemebond** [DarkPlacesEngine/darkplaces#141]
Any sounds originating under water should be muffled to everyone who hears it, even if they're not also under water. Currently, for example, rocket explosions sound the same--have the same volume and clarity--whether they explode in the air or under water.

**Comment by Baker7** [comment]
Does fteqw have an option to do this?  Just asking.

**Comment by hemebond** [comment]
FTEQW doesn't have any under-water acoustics active by default; neither when the player is under-water, nor when a sound source originates under-water. I don't see any setting related to it either. I'm assuming it's up to mods to implement via QuakeC.

**Comment by hemebond** [comment]
This was resolved with PR #140
