### ISSUE TITLE
Floor buttons not triggered when sv_gameplayfix_downtracesupportsongroundflag enabled

### ISSUE THREAD

**Issue by hemebond** [DarkPlacesEngine/darkplaces#144]
When `sv_gameplayfix_downtracesupportsongroundflag` is enabled (set to `1`) floor buttons are not triggered, e.g., at the end of e1m2.

**Comment by hemebond** [comment]
Oh, so it should never be used on vanilla Quake?

**Comment by Baker7** [comment]
In 2012 LadyHavoc made standard Quake default several settings that are best for Quake.  I haven't used that cvar much or at all.

This is what I know on the topic.

**Comment by hemebond** [comment]
Going to close this as it's not the default for Quake. Not sure what it's for if it doesn't work at all in Quake. Someone can re-open if it is supposed to work.
