### ISSUE TITLE
Sky in Zerstorer zer1m3 is red, not grey

### ISSUE THREAD

**Issue by hemebond** [DarkPlacesEngine/darkplaces#151]
Playing zer1m3 of the [Zerstorer mod](https://www.quaddicted.com/reviews/zer.html), the sky texture is grey, and renders correctly in Ironwail *and* old stable DarkPlaces:

![image](https://github.com/DarkPlacesEngine/darkplaces/assets/424218/45cdf86e-4d14-48d8-91d7-9ed6247e00cd)

but in DarkPlaces the sky is red:

![image](https://github.com/DarkPlacesEngine/darkplaces/assets/424218/15a069be-4c0d-4304-ad19-135c2823849f)

I've tested with a clean `id1` directory and still the same issue. I might have seen it in other custom mods/maps too.

**Comment by Baker7** [comment]
I loaded up DarkPlaces Beta from mid-2023 and has issue, but very early Zircon Beta does not have issue .. so I think this resolved it ...

https://github.com/DarkPlacesEngine/darkplaces/issues/105

The sky fix in Zircon Beta seems to fix this Zerstoerer issue.

**Comment by Baker7** [comment]
I'm not sure of the cause, I just know the fix.  It did it even when I loaded no other map, so cannot be sure of cause.

**Comment by hemebond** [comment]
The start map for the mod has the blood red sky, so it must be loading that at some point; even if I specify `+map zer1m3` on the command line.

**Comment by Baker7** [comment]
Yeah, where is that texture coming from?  I don't claim to know.
