### ISSUE TITLE
Start episode 2 gate message in different place

### ISSUE THREAD

**Issue by hemebond** [DarkPlacesEngine/darkplaces#158]
For some reason the popup message for episode 2 in start.bsp is at a different certical position of the screen compared to the other three gates. I don't see any difference in the trigger properties.

![dp20240402224027-00](https://github.com/DarkPlacesEngine/darkplaces/assets/424218/361ba0e4-b908-4e82-a359-14120e367771)
![dp20240402224033-00](https://github.com/DarkPlacesEngine/darkplaces/assets/424218/399cf99d-3e2c-476c-bd68-f6b8f62279f4)
![dp20240402224038-00](https://github.com/DarkPlacesEngine/darkplaces/assets/424218/bb8b2be5-eb92-48bf-bd7d-371630ec20fd)
![dp20240402224044-00](https://github.com/DarkPlacesEngine/darkplaces/assets/424218/3875bdfb-c001-47f6-bdbf-b653bf9a423e)

**Comment by Baker7** [comment]
There are more lines of text for that one.  This should be considered normal behavior for DarkPlaces.

This doesn't mean there isn't another way of doing it, but using a method that centers the text based off the number of lines of print, this is normal behavior.

```
// count the number of lines for centering
	scr_center_lines = 1;

```

Original WinQuake centers the lines too:

```
void SCR_CenterPrint (char *str)
{
	strncpy (scr_centerstring, str, sizeof(scr_centerstring)-1);
	scr_centertime_off = scr_centertime.value;
	scr_centertime_start = cl.time;

// count the number of lines for centering
	scr_center_lines = 1;
	while (*str)
	{
		if (*str == '\n')
			scr_center_lines++;
		str++;
	}
}

```

**Comment by Baker7** [comment]
Add however, why is your text so high up on the screen?

**Comment by Baker7** [comment]
Ok here is what is up ...

	if (scr_center_lines <= 4)
		y = (int)(vid_conheight.integer*0.35);
	else
		y = 48;

Episode 2 is reporting as 5 lines of text.
The others report as 4 lines of text.

The logic above treats those cutoffs very differently.

**Comment by Baker7** [comment]
If you change it, remember the center print is used for this ...

![dp20240402102439-00](https://github.com/DarkPlacesEngine/darkplaces/assets/160253/ae9eca66-99ab-4216-82f0-91411149c868)

**Comment by hemebond** [comment]
It's not nice behaviour. but if it's intended or default then I guess this can be closed. I only noticed the difference because I was testing center prints.
