### ISSUE TITLE
Side Effects Of DarkPlaces Beta Fiend Jump Fix In Quake Combat+

### ISSUE THREAD

**Issue by Baker7** [DarkPlacesEngine/darkplaces#164]
The fiend jump fix in DarkPlaces Beta causes this to occur in Quake Combat+ (the fiend jump fix in DarkPlaces Beta seems to work fine in regular quake).

![xon_20240407_physics_sliders](https://github.com/DarkPlacesEngine/darkplaces/assets/160253/215d3c73-0876-4d24-ad8d-148695cb69ad)
This dead body is not supposed to be sliding.

This may not be the only weirdness in physics  in Quake Combat+ caused by the DarkPlaces Beta Fiend Jump Fix.  There are some other things that seem off also, I hear some stuff bouncing and such.

Quake Combat+ uses gyro physics.  I suspect it is related to that.

Edict 3:

```
server EDICT 3:
modelindex     306
absmin         '1575.37195 1284.36011 175.03125'
absmax         '1609.37195 1318.36011 181.03125'
movetype       4
solid          3
origin         '1592.37195 1301.36011 200.03125'
angles         '0 248 -0'
avelocity      '0 -77 0'
classname      bodyque
model          progs/soldier_headshot.mdl
frame          140
mins           '-16 -16 -24'
maxs           '16 16 -20'
size           '32 32 4'
touch          bodyCheck()
health         26
takedamage     2
chain          entity 403
netname        progs/gib_soldfoot1.mdl
enemy          entity 1
flags          512
watertype      -1
owner          entity 202
th_pain        corpse_pain()
th_die         corpse_die()
semisolid      y
oldSolid       -1
original_frame 140
twitch_finished 61.1207314
just_been_shot 10008.5781
spin_direction 1
i_am_a_corpse  1
create_blood_puddle 10.7778492
create_blood_puddle_timer 10.7750998
create_blood_puddle_counter 13
gyro_dampeningeffect '1 1 1'
gyro_adampeningeffect '1 1 1'
gyro_object_mass 3700
gyro_object_resistance_air 1
gyro_object_resistance_water 1
gyro_object_resistance_slime 1
gyro_object_resistance_lava 1
gyro_object_pointcontent -1
gyro_object_channels 1
gyro_feedback  Gyro_Null()
gyro_objectlist_next entity 438
gyro_objectlist_prev entity 244
gyro_objectlist_inlist 1
scale          1
traileffectnum 210

```

**Comment by hemebond** [comment]
Does enabling `sv_gameplayfix_downtracesupportsongroundflag` have any effect?

**Comment by bones-was-here** [comment]
> Quake Combat+ is a refinement & continuation of Quake, SMC & Quake 1.5, built on Darkplaces

Built on which version? Probably one of the buggy versions that isn't compatible with id1, so the mod likely depends on the old bug and will need a patch to work on any non-bugged Quake engine.

**Comment by Baker7** [comment]
I haven't played with the any of the settings.

I am just documenting information that I know.

AKidd reported this as a bug for Zircon, I had made the fiend jump fix a cvar and then defaulted it off in the next version.
