### ISSUE TITLE
Falling Through The Floor Issues

### ISSUE THREAD

**Issue by Baker7** [DarkPlacesEngine/darkplaces#165]
In Quake Combat+ on E1M1 there is a "good guy" being killed.  And he proceeds to fall through the floor.

![xon_20240407_soldier_falls_thru_floor](https://github.com/DarkPlacesEngine/darkplaces/assets/160253/c8de8be4-5c38-4253-8735-3f957b48fb18)

In Quake3_Quake1, a single player mod I made from Xonotic maps and them customized them ( File: https://www.moddb.com/mods/zircon-engine/downloads/quake3-quake1-single-player-tech-demo-alpha-1 )

.. I am on an elevator going up ... then I simply fall through the floor.  I have not tested this one in latest Xonotic ...

![quake3_quake1_mod_geo_elevator_fall_through_floor](https://github.com/DarkPlacesEngine/darkplaces/assets/160253/eebb6665-ff06-4a4e-b18a-c41ce601d9a8)
In official DarkPlaces Beta from November ...

And now with current Xonotic Beta 2024 0407

Well .. it's a bit darker than I expected, but I know my way around the map ... and I still fall through the floor ...

![xon_20240407_geo_map_in_quake3_quake1_still_fall_thru_floor](https://github.com/DarkPlacesEngine/darkplaces/assets/160253/7a7ddfc4-bb39-4a7a-ab85-37ffffae10fd)

**Comment by hemebond** [comment]
In Quake 1.5, that is a `misc_actor` which _looks_ like it shouldn't have any physics applied to it:
```
void() misc_actor = 
{
...
	self.solid = SOLID_NOT;				// No world interaction
	self.movetype = MOVETYPE_NONE;		// Static item, no movement
	self.oldorigin = self.origin;		// Store for later
```

**Comment by bones-was-here** [comment]
> Load some maps, look at the console and make notes of how many have "droptofloor" fail issues. Realize that when you see that, an item or monster fell out of the map and realize those items are not falling out of the map in Ironwail or Quakespasm.

There's too many assumptions here, and conflation of things that aren't related.  In physics it's important to identify every distinction and detail.

The message doesn't say anything about falling, eg in alk1.2 start.bsp it says:  
`server VM warning: droptofloor at "880.000000 -176.000000 1169.000000": badly placed entity "misc_scientist", startsolid: 1 allsolid: 1`

In id1 (and Quake 3) entities don't fall if droptofloor() finds that they started in solid, they are simply deleted.  I don't know what alk1.2 does but it's QC's decision. Maybe in your mod, you run code that gives them negative z velocity.

When an entity bbox is already in a solid floor, it doesn't collide with that floor if it's moved down by tracebox() as the lower surface cannot make contact with the brush upper surface, so an entity placed in a solid _may_ fall, if such physics are applied to it.

**Comment by Baker7** [comment]
I'm documenting what I see.  When I have time, I'll check on some of those items in Alkaline and see if they are there in the autobuild and then see if they are there in Quakespasm.

**Comment by Baker7** [comment]
![xon_20240407_alk_caustic_no_guard](https://github.com/DarkPlacesEngine/darkplaces/assets/160253/600bf51d-d520-44f8-bac4-e2c3f4374cf1)

Map: alk_caustic ... in Xonotic Beta, the monster_dreadnaught is not there.

**Comment by Baker7** [comment]
I used Alkaline 1.2.

**Comment by Baker7** [comment]
All of the above, and https://github.com/DarkPlacesEngine/darkplaces/issues/109 are all the same issue ... the droptofloor changes made aounrd April 2023-May 2023.

**Comment by hemebond** [comment]
Same in Alkaline 1.2. The [spawn code](https://github.com/fabiolimamp/alkaline/blob/6367dc03001799157d2c47f1769e2e030ef2f576/monsters/dread.qc#L384) looks okay to me. Looks like it's dropping to floor before the entity is solid. Enabling `sv_gameplayfix_droptofloorstartsolid` works to fix the issue.

![image](https://github.com/DarkPlacesEngine/darkplaces/assets/424218/f9691c96-2d88-4d4a-bb84-2a3b616069ca)

**Comment by Baker7** [comment]
I thought you guys were defaulting sv_gameplayfix_droptofloorstartsolid to 1.

I saw another Issues thread where that was discussed and it sounded like that decision was made.

**Comment by Baker7** [comment]
So I set droptofloor start solid 1,

I am still getting ...
![xon_alk_caustic_droptofloor_solid_1](https://github.com/DarkPlacesEngine/darkplaces/assets/160253/a7770655-4918-43cf-8457-ffa1a7529818)

But you are not?

**Comment by hemebond** [comment]
> I thought you guys were defaulting sv_gameplayfix_droptofloorstartsolid to 1.

I think that was just for id1. Perhaps using `-game alk1.2` changes it.

I just tested again, and if I start the level as usual, he falls through the floor. However if I start with `sv_freezenonclients 1` and then disable it, he doesn't fall out of the level.

**Comment by Baker7** [comment]
It isn't doing 1 for Quake either

![xon_vanilla](https://github.com/DarkPlacesEngine/darkplaces/assets/160253/d26d6e26-1455-40f9-b285-5327a8948732)

**Comment by Baker7** [comment]
Here is Quake.  Game = id1.  Map format = Q1

Download of map:  
[geo_bones_q1.zip](https://github.com/DarkPlacesEngine/darkplaces/files/14921248/geo_bones_q1.zip)

Put that in id1 maps and you are ready to go.

Quakespasm:  I do not fall through floor of platform

![tall_quakespasm](https://github.com/DarkPlacesEngine/darkplaces/assets/160253/19c270f0-b728-4dc0-bce9-c05c09c92e1a)

Xonotic.exe -quake  ... I do fall through the floor of the platform .... 

![tall_xonotic](https://github.com/DarkPlacesEngine/darkplaces/assets/160253/fba1aa4f-d834-4971-8342-de0a6909d277)

**Comment by Baker7** [comment]
`I doubt very much that's related to droptofloor() detecting stuck entities, because it would be Very Weird for player physics to use that function (and that certainly isn't what engine physics does, and afaik all Quake games other than recent Xonotic use engine physics).
`
Build DarkPlaces Beta from March 2023.  Try these.  None of them happen until the droptofloor fix.

Build DarkPlaces Beta from May 2023.  Try these.  All of the problems listed above happen and the droptofloor fix was the change that occurred.

> I'm currently working on improving windows support because the people who use windows aren't maintaining it. I installed 10 on a spare laptop but it's a black hole for time, so intrusive and heavy with bloatware. Even after it's installed and fully updated, every other time I open the laptop to test a DP build, Windows thinks that's a good time to spend an hour or two installing more mandatory bloatware, and insists on uploading my darkplaces-sdl.exe to microsoft for "threat analysis" BEFORE allowing me to run it. 

It took me 2-3 months to fully neutralize Windows 10.  This helped: https://github.com/ionuttbara/windows-defender-remover/releases/tag/release_def_12_7_2  It actually removed the horror called Windows Defender that eat CPU whenever it likes.

I don't like the direction of Windows 10 or 11, but I am appreciative they haven't done anything truly horrible yet.

**Comment by bones-was-here** [comment]
I think you've missed a subtle change i suspect will be involved in the lift scenario

**Comment by Baker7** [comment]
I'm made out of a human,  I can make mistakes.

So in time, I look forward to seeing what you find.

**Comment by Baker7** [comment]
Thank you for the update.

I think I disagree with the philosophy you are using, though.

Does DarkPlaces Beta play correctly mods targeting classic DarkPlaces: NO.
Does DarkPlaces Beta play correctly mods targeting Quakespasm: NO

There aren't awards for special high-minded reasons for busted compatibilty, a user starts up an engine and either it plays the content right or it doesn't.

DarkPlaces Beta March 2023 with droptofloor start nonsolid plays mods targeting DarkPlaces Classic just fine.

DarkPlaces Beta March 2023 physics -- which Zircon Beta uses -- does not have the Dreadnaught fall through the floor with droptofloor start nonsolid .

What about the Rogue dudes that Hemebond noticed falling through the floors?

This is my point of view from what I see.  I understand the concepts of different goals and motivations so I can understand your point of view.

**Comment by bones-was-here** [comment]
I disagree with you, and point out that in your fork, id1 Quake is broken by default ;)

> it plays the content right or it doesn't

This is an oversimplification.  There's no one true correct behaviour because Q1BSP support is such a broken mess. The original implementation was buggy, the maps are buggy, and all the derivative Quake engines do different things and many of them are, or were, buggy. It simply isn't possible to support all content ever made for Quake with a single set of behaviours because different content assumes different engine behaviours. Any time we change a default we break someone's custom content because so many mods don't set any workaround cvars that they need and havn't added themselves to DP as a recognised mod with alternative defaults.

> Does DarkPlaces Beta play correctly mods targeting classic DarkPlaces: NO.

Classic DP was a bugfest, sorry if your stuff depended on some of those bugs.

> Does DarkPlaces Beta play correctly mods targeting Quakespasm: NO

Can you post an example of something that works in QSS but not DP? I think not.

You are ofc free to use the various sv_gameplayfix workaround cvars in your mod, I don't recommend it but they're there for a reason, and most engines don't offer them.

The Rogue lava men are placed incorrectly by the mapper, and are broken in some way in all engines.  The behaviour is different depending which one you test.  I'll probably add a cvar to DP to select which of the broken behaviours you want, but the only proper fix is to fix the map (eg with an .ent file).  We already discussed this in detail.
