### ISSUE TITLE
Is this a Darkplaces issue? WRATH crashes killing a specific enemy type

### ISSUE THREAD

**Issue by Swiss-Mac-User** [DarkPlacesEngine/darkplaces#166]
Hi there,
I have the following game crashing issue in WRATH (Wrathplaces macOS build), and not sure if the root of it may lie in the Darkplaces code - logs provided:

https://steamcommunity.com/app/1000410/discussions/1/4354491520967994752/

I am in exchange about this with the wrathplaces Mac source maintainer, but it's hard to tell if it's Quake source or WRATH specific root cause. Maybe somebody here has an idea?

**Comment by hemebond** [comment]
This version of DarkPlaces does not support Wrath, you need https://github.com/Official3DRealms/wrath-darkplaces
