### ISSUE TITLE
modlist.txt looks for mods in c:\ on windows

### ISSUE THREAD

**Issue by Baker7** [DarkPlacesEngine/darkplaces#172]
I noticed you guys gave some attention to modlist.xt.

A few weeks ago, I thought about making modlist.txt work.

I discovered it pokes away at the basedir of Windows looking for mods.

va(vabuf, sizeof(vabuf), "%s/", fs_basedir); <--- fs_basedir is usually ""

Take "%s/" and expand it --> "/" <-- you have your base drive folder.

(My thought since it just does a modname ... even if it did work that is not really "mod info", it's just a name -- so I ended up leaving it "broken" for now in my engine work.  That plus no mods that I know of even use it, not even Xonotic ... ).

**Comment by bones-was-here** [comment]
I changed it to use the working directory as the basedir if you don't specify it on the cmdline, have you tested the latest build?

If your working directory is c:\ and you didn't specify -basedir that would be user error ;)

**Comment by Baker7** [comment]
No, I haven't tested latest build.  Looks like non-issue then.
