### ISSUE TITLE
Remove Nexuiz-specific code and compile support

### ISSUE THREAD

**Issue by hemebond** [DarkPlacesEngine/darkplaces#179]
Nexuiz is no longer a thing, having switched to a different engine and forked into other projects. It doesn't seem necessary to keep its support around.

**Comment by Cloudwalk9** [comment]
Eventually if I finish my cmake system, Nexuiz would become a build preset of some kind for legacy/historical/backwards compatibility reasons but we do not wish to outright remove it.

**Comment by user1-github** [comment]
Hi, I accidentally stumbled upon this issue, so I just wanted to say this:

I understand that there are currently no plans to drop Nexuiz support in darkplaces, but if at some point it's eventually going to be dropped for whatever reason, I hope that at the very least it'll be done after the next stable release of darkplaces.

Me and others are huge fans of the original Nexuiz, and I get the best performance running it on the latest darkplaces code.

The original Nexuiz release binary from 2009, performs badly even on modern high end hardware.
There is also Rexuiz, which is a fork of Nexuiz with some small enhancements, but it uses its own fork of darkplaces that is based on some older upstream version. While it performs better than the original Nexuiz release binary, its still not as good as the original Nexuiz on the latest darkplaces and it also suffers from some stuttering issues.
