### ISSUE TITLE
Sawblade traps in Dissolution of Eternity are broken

### ISSUE THREAD

**Issue by SpecLad** [DarkPlacesEngine/darkplaces#18]
There are sawblades in levels R2M6 and R2M7 that are supposed to to back and forth across tracks, but instead they sort of shuffle in place. Reproducible with commit 7fabd734.

Example:

https://user-images.githubusercontent.com/2391761/147392247-8b01dc68-4832-4011-a051-10bd80993326.mp4

**Comment by hemebond** [comment]
This is still an issue on the latest master branch with new unstick stuff, but now there are `unstuck entity` messages, e.g.: `Unstuck entity 346 (classname "buzzsaw") with offset 0.000000 0.000000 2.000000.`

![image](https://github.com/DarkPlacesEngine/darkplaces/assets/424218/9ecfbce1-0baa-4dd2-aa41-e9e730a8d06b)
