### ISSUE TITLE
Turning with the keys is too fast

### ISSUE THREAD

**Issue by reignerdeustcher** [DarkPlacesEngine/darkplaces#183]
I like also to play quake with only keyboard and in dark places the turning when you press the keys to left and right is lightning fast, this wasn't like that in the original quake and also in vk quake, there's some console command or something for lowering that?

**Comment by hemebond** [comment]
`cl_yawspeed` controls keyboard turning speed. Defaults to `140`. What is a value that matches other Quakes?

```
cl_yawspeed is "140" ["140"] keyboard yaw turning speed
```

**Comment by reignerdeustcher** [comment]
> `cl_yawspeed` controls keyboard turning speed. Defaults to `140`. What is a value that matches other Quakes?
> 
> ```
> cl_yawspeed is "140" ["140"] keyboard yaw turning speed
> ```

thank you for the fast response =)

i put it in 90 and is much smoother, now only left to desactivate that fast strafe when pressing forward key but i think there's no way to change that

**Comment by hemebond** [comment]
> now only left to desactivate that fast strafe when pressing forward key but i think there's no way to change that

I don't know what this means. Is this different to the strafe speed of `cl_sidespeed`?

**Comment by hemebond** [comment]
I'm going to go ahead and close this since the speeds can be adjusted via the console.
