### ISSUE TITLE
''cvar_set: variable campaign not found''

### ISSUE THREAD

**Issue by reignerdeustcher** [DarkPlacesEngine/darkplaces#184]
I'm getting this error in the console and in the game when i run expansions like dimensions of the past, dissolution of eternity, etc, also the texts are screwed

**Comment by hemebond** [comment]
We really need some detail in order to determine if this is an engine bug or not. Screenshots, commands you've run, etc.

For the record I can play all mission packs and dopa without issue using the latest version.

**Comment by reignerdeustcher** [comment]
> We really need some detail in order to determine if this is an engine bug or not. Screenshots, commands you've run, etc.
> 
> For the record I can play all mission packs and dopa without issue using the latest version.

![dopa20240609015955-00](https://github.com/DarkPlacesEngine/darkplaces/assets/79814905/ae8aed5e-26a0-413d-8bb3-2f99106949c3)
![s-1](https://github.com/DarkPlacesEngine/darkplaces/assets/79814905/da689ac7-263e-4a2c-8a33-7dcde20e9e88)
![ss-5](https://github.com/DarkPlacesEngine/darkplaces/assets/79814905/08b2cb94-7441-4471-b642-2beb60f1555e)

it happens without changing any command, i run from the shorcuts like this: 

@echo off
start darkplaces -game dopa

**Comment by hemebond** [comment]
Ouch, that's a really old version of DarkPlaces unfortunately. I'm not seeing it in the latest code.

Does the mod not work due to this issue? Or is it just a message?

**Comment by reignerdeustcher** [comment]
> Ouch, that's a really old version (May 13 2014) of DarkPlaces unfortunately. I'm not seeing it in the latest code.
> 
> Does the mod not work due to this issue? Or is it just a message?

sometimes it crashes

but that old version is the only that i see, where's updated ones?

**Comment by hemebond** [comment]
There are a few links on https://hemebond.gitlab.io/darkplaces-www/engine/ to a newer beta release.

**Comment by reignerdeustcher** [comment]
> There are a few links on https://hemebond.gitlab.io/darkplaces-www/engine/ to a newer beta release.

sadly is the same =(

![dopa20240609134948-00](https://github.com/DarkPlacesEngine/darkplaces/assets/79814905/2fd2fe88-5c6c-43de-987e-3a78ceae273b)

**Comment by hemebond** [comment]
Ah, it seems that cvar was only added three years ago in 727c2cb which means you'll need a much newer version. Unfortunately there are still no newer releases for Windows so you'd have to compile it yourself.

**Comment by reignerdeustcher** [comment]
> Ah, it seems that cvar was only added three years ago in [727c2cb](https://github.com/DarkPlacesEngine/darkplaces/commit/727c2cbec73fbd199cef8e78c5403ae607f56347) which means you'll need a much newer version. Unfortunately there are still no newer releases for Windows so you'd have to compile it yourself.

how can i do to compile it?

and another little problem: the center view key doesn't work, it does nothing, no matter if i change it to different letters

**Comment by hemebond** [comment]
> how can i do to compile it?

Instructions are in the README on the front page.

> and another little problem: the center view key doesn't work, it does nothing, no matter if i change it to different letters

Please create a new bug ticket for this one. I can confirm that it doesn't seem to work in the latest version also.
