### ISSUE TITLE
Quake world servers are no longer detected.

### ISSUE THREAD

**Issue by Gibitwit** [DarkPlacesEngine/DarkPlaces#194]
When choosing the Quake world option for multiplayer no servers are found.  Other engines do find the servers and they are also listed on gametracker.com.  I am not sure when this started, I think it was after the release of Quake Enhanced by Night Dive studios.  Maybe the server addresses were changed.

Using the 20170829beta1 version of DarkPlaces.

**Comment by bones-was-here** [comment]
When I open that menu in current DP, many QW servers are listed after a few seconds. The `net_slistqw` command works fine too.  
The version you're using is unsupported, and rather ancient...

**Comment by Gibitwit** [comment]
Are there any later release builds that work?  There are builds in Linux repositories, but there is nothing for Mac and windows users.

**Comment by bones-was-here** [comment]
The Xonotic engine build linked on the readme https://github.com/DarkPlacesEngine/DarkPlaces?tab=readme-ov-file#downloading-and-running updates about half an hour after a commit is pushed to master.  
The only differences between this and a Quake build are the file name (DP uses it to decide which game it's running, the default is `darkplaces-sdl`) and the icon.  At some point I'll setup a build with the default file name and icon...

Windows and Linux are well maintained, Mac not so much (I don't have one).

**Comment by Gibitwit** [comment]
Using the latest build (September 3) from that link for Windows and Linux, the Quake world servers still are not found.

I tried installing and enabling UPnP on the Router, but no Quake World servers were found.

**Comment by bones-was-here** [comment]
Ok well more info would be needed to do anything about it, because it works for me: 2/4 masters respond with a list of ~760 live servers.  
You could try enabling this cvar to get more info in console: `net_slist_debug 1`

**Comment by Gibitwit** [comment]
Querying servers with net_slist_debug on, crashes the game.
![Clipboard_09-04-2024_01](https://github.com/user-attachments/assets/30b1b8c3-a4de-4835-8852-601fb007bcb7)

**Comment by bones-was-here** [comment]
I fixed the crash in dfe66229824823f849c788e84f89d4b4b275d594.  Do you have master servers configured? There's 4 by default but I think only 2 are still running. You can check with `find sv_qwmaster`.

**Comment by Gibitwit** [comment]
It looks for 4 masters servers but they all time out.  In the multiplayer menu it says port 26000, but in the console for the master servers it has the number 27000 after their addresses.

**Comment by bones-was-here** [comment]
Yes master servers have different default ports than quake servers, and their admins may use any port.  

I've updated the QW master list in 67ffc8e78f2716964384526456ee6eb0365b4ebe: added a new one, removed a dead one, removed a duplicate.  
With `net_slist_debug 1` it should look like this in console (when you open the QW server list in the menu):
```
Querying QW master, favourite and LAN servers, reset=1
Querying QW master 78.47.113.68:27000 (resolved from master.quakeservers.net:27000)
Querying QW master 5.9.97.180:27000 (resolved from qwmaster.fodquake.net:27000)
Querying QW master 194.48.213.75:27000 (resolved from master.quakeworld.nu:27000)
Received QuakeWorld server list from master.quakeservers.net:27000
Received QuakeWorld server list from qwmaster.fodquake.net:27000
Received QuakeWorld server list from master.quakeworld.nu:27000
Finished querying 0 DP 3 QW masters and 786 servers in 22.419050 seconds
Finished checking server timeouts in 0.007843
```

I suspect a firewall or sandbox or router setting is blocking your connection to the masters, and maybe to the servers too...

**Comment by Gibitwit** [comment]
I am suspicious it may be the router, there has been much trouble with OpenWRT on this model.

Strange that Darkplaces servers are reachable but not Quake World.  Other engines do find the Quake World servers.  I'll try flashing the router to an older version.

**Comment by Gibitwit** [comment]
I don't think so, but I read something about maybe combining small packets.

I still need to try some older OpenWRT versions.  I think the problem started in November or January.
