### ISSUE TITLE
renderscene broke between November 2023 and April 2024?

### ISSUE THREAD

**Issue by Baker7** [DarkPlacesEngine/DarkPlaces#224]
This mod does 2 renderscene to do a Rear View Mirror:
Download with QuakeC source: https://www.moddb.com/mods/zircon-engine/downloads/csqc-rear-view-mirror

Zircon Beta:

![renderscene_zircon_beta](https://github.com/user-attachments/assets/1cf1c3e3-52cc-4576-b001-e105ed562772)

DarkPlaces Beta November 12 2024:

![renderscene_xon_nov_12_2024](https://github.com/user-attachments/assets/6e327704-f075-4840-bec4-52a40f346cae)

Renders the same in DarkPlaces Beta April 7 2024, however, it works in a DarkPlaces Beta .exe I have from late 2023 which was likely from September DarkPlaces Beta GitHub 2023 source code.

The CSQC looks like this ... it is a 2nd renderscene call after rendering fullscreen, it renders 1/4 size in the top right corner as follows:

```
void D_RearViewMirror_Draw_3D ()
{
	if (!autocvar_showmirror)
		return;

	vector viewport_size = [ov.vid_width * 0.25, ov.vid_height * 0.25];
	
	// Baker: This is putting in the RIGHT TOP corner, except giving it small margin.
	vector viewport_pos  = [ov.vid_width - viewport_size.x, 0];
	
	viewport_pos += [ov.vid_width * -1/32, ov.vid_height * 1/16]; // Give it some margin.
	
	vector vfov	= GetCurrentFovEx(viewport_size, ov.viewzoom, ov.fov); // vid_width must update first

	vector viewangles_180 = getpropertyvec (VF_CL_VIEWANGLES);
	viewangles_180.y += 180; // Do a 180 turn

	// Render the Scene
	clearscene			();			// wipe entity lists. reset view properties to their defaults.

	//setproperty			(VF_VIEWPORT, '0 0 0', '320 240 0');
	setproperty			(VF_VIEWPORT, viewport_pos, viewport_size);
	setproperty			(VF_DRAWWORLD, 1);	
	setproperty			(VF_ANGLES, viewangles_180);	
	setproperty			(VF_FOV, vfov);
	addentities			(MASK_NORMAL_4 | MASK_ENGINE_1); // Baker: Note the lack of MASK_ENGINEVIEWMODELS_2

	// Baker: Sadly we need to do this ...
	// ONLY because we cleared the scene above.  If we don't do this, the main window
	// will not get a status bar.

	float will_draw = autocvar_zr_suppress_engine_statusbar ? draw_statusbar_false : draw_statusbar_true;
	float is_croshair = (ov.is_dead_view == false && intermission == intermission_not_0 && ov.is_in_cutscene == false);

	setproperty			(VF_DRAWENGINESBAR, will_draw);	
	setproperty			(VF_DRAWCROSSHAIR, is_croshair);

	// renderscene: draw the scene to the screen using the various properties.  
	renderscene (); // #304
}



```

**Comment by hemebond** [comment]
It's really difficult to test with QuakeC that uses custom functions and globals. Do you have a simpler use-case we can drop into mostly vanilla code?

**Comment by hemebond** [comment]
What is `GetCurrentFovEx`? I'm struggling to get anything like a PiP to render with the code provided.

**Comment by Baker7** [comment]
Here is function ...

`vector GetCurrentFovEx (vector vsize, float current_viewzoom, float fov)
{
	float frustumy	= tan(fov * ONE_HALF_DEGREE_IN_RADIANS_0_087_) * 0.75 * current_viewzoom;
	float frustumx	= frustumy * vsize.x /*ov.vid_width*/ / vsize.y /*ov.vid_height*/ / ov.vid_pixelheight;
	float fovx		= atan2(frustumx, 1) / ONE_HALF_DEGREE_IN_RADIANS_0_087_;
	float fovy		= atan2(frustumy, 1) / ONE_HALF_DEGREE_IN_RADIANS_0_087_;

	return '1 0 0' * fovx + '0 1 0' * fovy;
}

vector GetCurrentFov (float current_viewzoom, float fov)
{
	return GetCurrentFovEx ([ov.vid_width, ov.vid_height], current_viewzoom, fov);
}
`

**Comment by hemebond** [comment]
I disabled the vfov calculation stuff because there's a variable in there, `vid_pixelheight`, that I don't know about and caused divide by zero errors/warnings. Seemed to work fine without it.

![raiders20241201014811-00](https://github.com/user-attachments/assets/c3bbc59f-b793-48c0-b5f5-27ad397f0124)

**Comment by hemebond** [comment]
@Baker7 Can we close this issue? Seems to work fine at least in the latest version.

**Comment by Baker7** [comment]
Your picture in picture example doesn't have a gun.  

Add MASK_ENGINEVIEWMODELS to addentities for the big window.  And remove it for the little window so ..
1. The big window has a gun
2. The little window does not have a gun.

You will find you cannot do this, but you could with DarkPlaces Beta September 2023.

The bug is that clearscene -- I am guessing --- is clearing the render buffer (which it shouldn't do)?

Picture in picture is the main reason for this feature and the bug is that is that somewhere between September 2023 and April 2024, it got broken so it can't picture in picture with a different entity set.

**Comment by hemebond** [comment]
I thought the bug was that it didn't render the big view at all. Adding the gun was just a case of adding `MASK_ENGINEVIEWMODELS`.

![image](https://github.com/user-attachments/assets/a6bf20e5-1e0d-4373-ac9c-f5c9bbf02477)

**Comment by Baker7** [comment]
Can I get your CSQC QuakeC source code for the above?

**Comment by hemebond** [comment]
```c
void D_RearViewMirror_Draw_3D(float vid_width, float vid_height) {
	vector viewport_size = [vid_width * 0.25, vid_height * 0.25];

	vector viewport_pos = [vid_width - viewport_size.x, 0];
	viewport_pos += [vid_width * -1/32, vid_height * 1/16]; // Give it some margin.

	vector viewangles_180 = getpropertyvec(VF_CL_VIEWANGLES);
	viewangles_180.y += 180; // Do a 180 turn

	clearscene();  // wipe entity lists. reset view properties to their defaults.

	setproperty(VF_VIEWPORT, viewport_pos, viewport_size);
	setproperty(VF_DRAWWORLD, TRUE);
	setproperty(VF_ANGLES, viewangles_180);
	addentities(MASK_NORMAL | MASK_ENGINE);

	setproperty(VF_DRAWCROSSHAIR, TRUE);
	setproperty(VF_DRAWENGINESBAR, TRUE);

	renderscene(); // #304
}


void CSQC_UpdateView(float width, float height, float menushown) {
	clearscene();
	addentities((intermission ? 0 : MASK_NORMAL) | MASK_ENGINE | MASK_ENGINEVIEWMODELS);
	setproperty(VF_DRAWCROSSHAIR, TRUE);
	setproperty(VF_DRAWENGINESBAR, TRUE);
	renderscene();

	D_RearViewMirror_Draw_3D(width, height);
}
```

**Comment by Baker7** [comment]
Go ahead and close the issue.  

Clearly you were able to make it work, maybe a cvar changed behavior like vid_pixelheight ... whatever the case is I will post a comment identifying the cause, but apparently the functions themselves work fine.
