### ISSUE TITLE
checkextension for EXT_CSQC fails

### ISSUE THREAD

**Issue by hemebond** [DarkPlacesEngine/DarkPlaces#225]
Trying to test if CSQC is available in the latest DarkPlaces but the check always fails:

```c
float checkextension(string s) = #99;
void() worldspawn =
{
	dprint("worldspawn()\n");

	if (checkextension("EXT_CSQC")) {
		dprint("CSQC is available\n");
	}
	else {
		dprint("CSQC is NOT available\n");
	}
```

And the console output:

```
worldspawn()
CSQC is NOT available
```

**Comment by Baker7** [comment]
https://github.com/DarkPlacesEngine/DarkPlaces/blob/master/svvm_cmds.c

Line 235 ...

```
"ZQ_PAUSE",
"DP_RM_CLIPGROUP",
NULL
//"EXT_CSQC" // not ready yet
};
```

If you are the server, is CSQC actually available?

**Comment by hemebond** [comment]
> If you are the server, is CSQC actually available?

Ah, interesting thought. This isn't a dedicated server, but I was testing with coop. However, even starting "single-player" doesn't work:

`/darkplaces-sdl -game raiders +developer 2 +sv_cheats 1 +coop 0 +deathmatch 0 +map e1m1`

So now I'm confused if it's _supposed_ to work, and _how_ it would work. How do I enable CSQC features on clients that support it?

**Comment by Baker7** [comment]
For one thing, clients that don't support CSQC won't run the csprogs.dat and will simply ignore it.

**Comment by hemebond** [comment]
> For one thing, clients that don't support CSQC won't run the csprogs.dat and will simply ignore it.

Right, but how do I, for example, tell CSQC clients to generate particles in CSQC while generating particles in SSQC for clients that do not?

I'm thinking maybe this kind of setup just isn't supported, and I need one or the other.

**Comment by Baker7** [comment]
One option would be check extension for DP_CSQC_SPAWNPARTICLE to tell the difference.

**Comment by hemebond** [comment]
Closing as this will not work as intended. Discussed it with Spoike and it seems I would need to set flags on players. Much easier to just move particles to CSQC and require DarkPlaces or FTEQW.
