### ISSUE TITLE
CSQC - clearscene() clear-color incorrectly set to VF_FOG_COLOR / should be no color or transparent.

### ISSUE THREAD

**Issue by Subject9x** [DarkPlacesEngine/darkplaces#31]
example: when CSQC calls _clearscene()_ and CSQC has set _setproperty(_ VF_DRAWWORLD, 0 _)_ , the background color of the render window ( using VF_MIN, and VF_SIZE) is totally random - but usally uses the VF_FOG_COLOR value.

I've set my CSQC to render 2 mini viewports during gameplay. 1 viewport is a black background (serviceable) but the other display ends up the VF_FOG_COLOR.

Is there anyway to enforce a black background?

preferably there's an option for alpha transparency.

**Comment by Cloudwalk9** [comment]
Might be related to fog being incorrectly applied to UI elements. I fixed most of those but this might be a straggler.

**Comment by Subject9x** [comment]
![image](https://user-images.githubusercontent.com/12732481/159822115-c3316530-90b1-462b-915a-72d470000ded.png)

``` clearscene();
      setproperty(VF_ORIGIN, viewOrg + [-150 - xHalf, 0, 70 + zHalf]);	//look towards it.
      setproperty(VF_ANGLES, '30 0 0');
      
      setproperty(VF_MIN, vtodpp([panelOrg_x, panelOrg_y, 0]) );
      setproperty(VF_SIZE, vtodpp([siz_x, siz_y, 0]) );
      setproperty(VF_FOV, [zTotal, atan(siz_y/(siz_x/tan(zTotal/360*6.28))) * 360/6.28, 0]); 

      setproperty(VF_DRAWENGINESBAR, FALSE);
      setproperty(VF_DRAWWORLD, FALSE);
      setproperty(VF_DRAWCROSSHAIR, FALSE);
      
      setproperty(VF_FOG_DENSITY, 0.0);
      setproperty(VF_FOG_ALPHA, 0.0);
      setproperty(VF_FOG_COLOR, '0 0 0');
      setproperty(VF_FOG_START, 0.0);
      setproperty(VF_FOG_HEIGHT, 0.0);
      setproperty(VF_FOG_FADEDEPTH, 0.0);
```

**Comment by Cloudwalk9** [comment]
Assuming that bottom left panel is the one supposedly following fog color? Looks like it.

**Comment by Subject9x** [comment]
sorry, I should have specified. Yes the lower left panel is the 3D Viewport in question that is using the FOG_COLOR.

**Comment by drwakey** [comment]
Have you tried changing the value of the cvar r_fog_clear?
By default it is set to 1 which "clears renderbuffer with fog color before render starts".

**Comment by Subject9x** [comment]
> Have you tried changing the value of the cvar r_fog_clear? By default it is set to 1 which "clears renderbuffer with fog color before render starts".

I think I ended up finding that a few months ago, I'll close this because it works iirc.
