### ISSUE TITLE
HTTP download progress no longer shown

### ISSUE THREAD

**Issue by garymoon** [DarkPlacesEngine/darkplaces#37]
When connecting to a server requiring new assets to be downloaded over http, there is no longer any visual indication in the info bar of that occurring. In previous versions the download queue was displayed with active downloads indicating progress and speed. This area now indicates which connection stage the client is in, which is a great addition, but the download indication is completely missing. Depending on the size and speed of the asset download, this gives the user the impression that the connection is timing out or otherwise failing to progress. It would be great if both could be indicated.

New:
![image](https://user-images.githubusercontent.com/4531887/160888456-645025c5-c93f-4d00-989a-16be44188055.png)

Old:
![image](https://user-images.githubusercontent.com/4531887/160888686-1ab58718-71f2-4da2-a6fe-ffd97bc82835.png)

**Comment by LegendaryGuard** [comment]
I was digging a bit in the source code about these details.

The new one is located here:
https://github.com/DarkPlacesEngine/darkplaces/blob/fe7a27c1f9ee6904eddecd54f0fcae461806d43c/cl_screen.c#L1683

The old one looks like is here:
https://github.com/DarkPlacesEngine/darkplaces/blob/0207a10e1576d5ebe67730b5b98709383613f4df/cl_screen.c#L572

**Comment by bones-was-here** [comment]
Same bug as https://gitlab.com/xonotic/darkplaces/-/issues/256 introduced in fcb34623c43f76179a495f03672b7fe9543e23ea and fixed in 7dedbcb24623a668a1a3229c77e7b1094196cd35
