### ISSUE TITLE
I get this error during launch, but engine starts.

### ISSUE THREAD

**Issue by kotenok2000** [DarkPlacesEngine/darkplaces#38]
"the procedure entry point inflateValidate not  found in dll library E:\Program Files\qemu\libpng16-16.dll"
If i rename the file to libpng16-16.dll.1 error disappears.
It happened on 2014 version and freshly mingw64 compiled https://github.com/DarkPlacesEngine/darkplaces/commit/0207a10e1576d5ebe67730b5b98709383613f4df

**Comment by Cloudwalk9** [comment]
Are you running DarkPlaces from E:\Program Files\qemu? Like, is the darkplaces-sdl.exe binary located there?

**Comment by kotenok2000** [comment]
No. it is located at E:\new folder\darkplaces\darkplaces-sdl.exe

**Comment by Cloudwalk9** [comment]
Windows looks for DLLs in a specific search order. Are you running darkplaces by double clicking on the binary in the GUI, or opening it from a console or terminal?

**Comment by kotenok2000** [comment]
Double clicking.

**Comment by Cloudwalk9** [comment]
Do you have E:\Program Files\qemu in your PATH environment variable?

**Comment by kotenok2000** [comment]
Yes. I am able to run qemu-img.exe from  E:\new folder\darkplaces

**Comment by Cloudwalk9** [comment]
I see. Do you have Discord, an IRC client, or Matrix? I would like to troubleshoot this further.

**Comment by kotenok2000** [comment]
Yes. I have discord.
kotenok2000#0530
