### ISSUE TITLE
Black and transparent elements in maps

### ISSUE THREAD

**Issue by h0tc0d3** [DarkPlacesEngine/darkplaces#46]
In xonotic some maps like mental-gap-beta4 show black shadows instead of jump pads, in maps like toxicity teleports is empty and transparent, also in some maps doors transparent. In FT frost not visible.
The map c-fun-v1r1 loaded completely black.
The problem affects apparently old maps. New maps don't have this problem. 
In dlcache, all maps load successfully and their checksums match. If these maps are loaded simply in xonotic, then they are displayed normally. 
The problem occurs only when starting these maps from the server and server set `sv_onlycsqcnetworking 1`.

With `sv_onlycsqcnetworking 0` the problem does not appear.

```
sv_onlycsqcnetworking disables legacy entity networking code for higher performance
(except on clients, which can still be legacy)
```

**Comment by bones-was-here** [comment]
I believe this will need to be fixed in Xonotic QC, and there's no need to double post the same issue on both trackers.
