### ISSUE TITLE
[ft2] The way of DarkPlaces to render text is unfriendly to CJK text

### ISSUE THREAD

**Issue by NaitLee** [DarkPlacesEngine/darkplaces#49]
**Brief Description**

The way of DarkPlaces to render text is unfriendly to CJK text.
There is too much overhead on "caching", causing bad game performance.
Good fixing should be possible, by reworking on that part.

Below is detailed analysis. Idea to solution is at bottom.

**Symptom**

The game will "lag" for few frames when showing individual CJK string for the first time.
It's simply annoying, period.

The impact of the game Xonotic is described [here in Xonotic Forums](https://forums.xonotic.org/showthread.php?tid=9497). In which reply [#11](https://forums.xonotic.org/showthread.php?tid=9497&pid=88826#pid88826) also have explanation, but you may want to read this issue instead.

**Basic Concepts**

- CJK: Shorthand for Chinese/Japanese/Korean.  
  CJK characters are so many, occupying large amount of Unicode code space of Plane 1. Just common "CJK Unified Ideographs" range from U+4E00 to U+9FFF, that's 20992 ones.

- The way of DarkPlaces to render text:
  - DP will render (from ttf/otf) & cache the font texture as *maps*, on demand if required, as seen around [here](https://github.com/DarkPlacesEngine/darkplaces/blob/f16954a9d40168253ac5d9890dabcf7dbd266cd9/gl_draw.c#L1265). Rendering is resource-costing, but only once.
  - By default a *map* is 16x16 chars in size, as in [these constants](https://github.com/DarkPlacesEngine/darkplaces/blob/f16954a9d40168253ac5d9890dabcf7dbd266cd9/ft2_fontdefs.h#L6); that means 256 chars will be rendered, *whenever a single character among them is on the way*, as in [this `for` loop](https://github.com/DarkPlacesEngine/darkplaces/blob/f16954a9d40168253ac5d9890dabcf7dbd266cd9/ft2.c#L1377)
  - At very start DP will cache the very first ASCII chars, that means languages like English will only need one or two additional maps -- DP just use the cached ones all the way
  - It's applicable to most of Western languages, and is indeed working well

**But**, matter is going different on CJK text.

- A typical Chinese sentence have several characters
- But, unlike Western languages, *the chars will spread across several "maps"*
- The worst case is that *every* character will cause a fresh "map" to be rendered & cached, *and that's the usual case*
- That further tells, about 255x of the effort is overhead. More than that, most of cached chars are *uncommon* and won't ever be used in the game, so isn't optimal at all

So, when players use CJK language:

- Earlier in the game, players will experience graphical lag very often. It's very unpleasant in a fast-paced game like Xonotic
- Though, it's lesser after caching many of the maps. But of course higher the memory cost.
- Well, not the end yet: the texture cache slots have limit (I see Xonotic have 1024), *they will run out, sooner or later*, after that following in-game textures will appear to be gibberish (indeed becoming texture of the first font map), only restarting the game can save
- Experience the fear again from the begining!

**What can help?**

I had some trials to reduce the matter, but they are ineffective to the real problem.

<details>
<summary>Click to expand anyway</summary>

To decrease chars-per-map:

- Yes, by halving the count, the game become far less laggy. But the overhead is still there, useless chars are still rendered, and cache slots run out even more quickly.

To increase chars-per-map:

- Only see segmentation faults, by out-of-memory. It isn't realistic to put all of the chars in few maps either.

To increase cache slots:

- Not so good. As said, it runs out *sooner or later*.
</details>

The only future-keeping approach in my mind is to rewrite the corresponding procedure, to:

*When encountered those CJK chars, instead of regular mapping, reserve some kind of special texture map, to cache the only used chars, incrementally, one by one. And also keep an array map, query existing chars with that.*

And that's all other games around (free or proprietary) are doing: only used chars are in the assets.

----

Thanks for the Great engine, flexible like that! Best wishes :)

**Comment by NaitLee** [comment]
I don't know if I should take the coding job.
I didn't write much C.

Let me know if active members will do it, or is left to me :)

**Comment by NaitLee** [comment]
I think I will give it a try to solve the problem :)

Wait for me

**Comment by Blub** [comment]
> I think I will give it a try to solve the problem :)

You'd need some efficient map/tree from glyph to texture, and a way to allocate blocks in the current texture.
IIRC the lightmap allocator (`Mod_AllocLightmap_*` function family) might be usable for this - but it pins rows to specific sizes, so you probably want to round up the glyph sizes to a multiple of some sane value that doesn't waste too much space either way.

**Comment by NaitLee** [comment]
Thanks for advice!

I had some progress, it worked "a bit", but now polluted by segfaults 🙃

(`gdb` can't help further, it became totally random. I think I should start over.)

It may take a long time and I can't make promise... wish I have luck...

----

After that are some questions,

- Is it ok to use 8.5 + 4.25 MiB memory to keep the records? Like this:
```c
#define UNICODE_SIZE 0x110000
static ft2_font_map_t *character_to_map_mapping[UNICODE_SIZE] = {0};
static int character_to_map_index_mapping[UNICODE_SIZE] = {0};
```
- Is it ok to add new functions? I've wrote a `FontMap_GetForChar`, to find a map or load one if not present.
  Note: I won't change existing functions ("apis"), as said in guideline
- Is it ok to do large-scale modification to a large function like `Font_LoadMap`?  
  Or better in my mind, split its content to several other functions for reusing them?  
  Because I feel more `if`s ("bigblocks" or not) will make it spaghetti code 🙃
- Where should we discuss security-related problems? Didn't find one around here...

----

BTW those "bigblocks" in Unicode:

```c
static Uchar unicode_bigblocks[] = { 
	0x3400, 0x4DBF, 	//   6592  CJK Unified Ideographs Extension A
	0x4E00, 0x9FFF, 	//  20992  CJK Unified Ideographs
	0xAC00, 0xD7AF,		//  11184  Hangul Syllables
	0xE000, 0xF8FF, 	//   6400  Private Use Area
	0x10000, 0x10FFFF 	//         Everything above
};
```

**Comment by Blub** [comment]
> * Is it ok to add new functions? I've wrote a `FontMap_GetForChar`, to find a map or load one if not present.
>   Note: I won't change existing functions ("apis"), as said in guideline
> 
> * Is it ok to do large-scale modification to a large function like `Font_LoadMap`?
>   Or better in my mind, split its content to several other functions for reusing them?
>   Because I feel more `if`s ("bigblocks" or not) will make it spaghetti code upside_down_face

I'd argue factorizing parts into smaller chunks is always a good idea, particularly `static` helpers aren't public APIs anyway.
Plus it sounds like it'll probably be easier for you if you can get it working first and then clean it up using the feedback you get on the patches directly.

> * Is it ok to use 8.5 + 4.25 MiB memory to keep the records? Like this:

Hm. I haven't really thought about the size of it. Doesn't seem that big :-)
And even if there are supported platforms where that's a lot (I don't know), the current code is probably worse still.

**Comment by NaitLee** [comment]
I progressed a bit in #52.

I've eventually managed to solve that bogo segfault, so no rewrite or code split took place (yet).

Let's continue there...

**Comment by goodspeed34** [comment]
I suggest we introduce a new data structure for font cache.

>  Yes, by halving the count, the game become far less laggy. But the overhead is still there, useless chars are still rendered, and cache slots run out even more quickly.

This is true. If we decrease it to 8x8, the worst case will be 63 chars. The overhead is still there.

While preserving the original map struct, we can create an character index so that we can use it like a linked list. We can only use that for CJK characters.

Because the common characters in CJK (at least in Chinese) wan't that much. In chinese, there are 3500 common characters which will fit in 14 maps. The overhead is the iteration and `if` statements. In the worst case, there will be about 3500 `if` statements failed which is not a problem for modern CPUs.

Note: Making it double-linked seems useless because we would already iterated to the last map to search whether it was there.

**Comment by NaitLee** [comment]
I didn’t mention another matter: users can generate text content by nicknames and chatting. Think about an edge case, if there’s an international big server with players from all around the world, the same problem may happen.
every unicode character can be sent in chat. with this problem there malicious client can put graphical clients in trouble.
So the strategy should not just for CJK, but also for `>= U+10000` and when most of the cache slots are occupied.

> While preserving the original map struct, we can create an character index so that we can use it like a linked list. We can only use that for CJK characters.
> 
> Because the common characters in CJK (at least in Chinese) wasn't that much. In chinese, there are 3500 common characters which will fit in 14 maps. The overhead is the iteration and `if` statements. In the worst case, there will be about 3500 `if` statements failed which is not a problem for modern CPUs.
> 

That’s the idea of #52 :) An essential part left there is incremental rendering — sadly I didn’t get any relative function to work.

**Comment by NaitLee** [comment]
Ouch, I tried it 2 times but the result is unsatisfactory 🤕
The biggest problem is inability to update the big map texture with small overhead.

**But** at the moment I have new idea:
- for the first incoming 256 bigblock characters, just use 1x1 maps, serve them upon request of rendering (to related `gl_draw.c` functions)
- after the 256th character, merge previous characters (data) to a complete map, then serve this one instead, free/unload those small maps
- it’s even better to merge them gradually, to save computing power  
  e.g. upon 1 new character is requested, merge 128/64/32 of previous 1x1 maps  
  (let’s don’t forget the overall goal: reduce/remove computation overhead)

This way there’s no need to “keep and preserve texture data and mess it up” 🙃

In comparison to previous approaches, this is a “lazy” version, seems easier to understand & do, but I should really re-write my patch, for have touched too many things.

**Comment by NaitLee** [comment]
I started yet another trial to fix this, and fortunately it’s going to complete and give a good overall performance.
