### ISSUE TITLE
build in osx 

### ISSUE THREAD

**Issue by 3453-315h** [DarkPlacesEngine/darkplaces#51]
have osx 10.15.7
 followed the instructions in the readme (so everything is installed)

yet upon make sdl-release 

❯ make release
/Library/Developer/CommandLineTools/usr/bin/make sv-release sdl-release
/Library/Developer/CommandLineTools/usr/bin/make bin-release \
		DP_MAKE_TARGET=macosx \
		EXE='darkplaces-dedicated' CFLAGS_FEATURES='' LDFLAGS_COMMON='-lm  -lz     -ldl' LEVEL=1

========== darkplaces-dedicated (release) ==========
/Library/Developer/CommandLineTools/usr/bin/make prepare BUILD_DIR=build-obj/release/darkplaces-dedicated
mkdir -p build-obj/release/darkplaces-dedicated
cp -f makefile.inc build-obj/release/darkplaces-dedicated/
cp -f makefile build-obj/release/darkplaces-dedicated/
/Library/Developer/CommandLineTools/usr/bin/make -C build-obj/release/darkplaces-dedicated darkplaces-dedicated \
		DP_MAKE_TARGET=macosx \
		CFLAGS='  -MMD   -Wall -Winline -Werror=c++-compat -Wwrite-strings -Wshadow -Wold-style-definition -Wstrict-prototypes -Wsign-compare -Wdeclaration-after-statement -Wmissing-prototypes -DLINK_TO_ZLIB  -DUSEXMP   -D_FILE_OFFSET_BITS=64 -D__KERNEL_STRICT_NAMES -I../../../    -O3 -fno-strict-aliasing -fno-math-errno -fno-rounding-math -fno-signaling-nans -fno-trapping-math'\
		LDFLAGS='-O3 -fno-strict-aliasing -fno-math-errno -fno-rounding-math -fno-signaling-nans -fno-trapping-math -DSVNREVISION=`{ test -d .svn && svnversion; } || { test -d .git && git describe --always; } || echo -` -DBUILDTYPE=release -lm  -lz     -ldl' LEVEL=2
make[3]: `../../../darkplaces-dedicated' is up to date.
strip darkplaces-dedicated
/Library/Developer/CommandLineTools/usr/bin/make bin-release \
		DP_MAKE_TARGET=macosx \
		EXE='darkplaces-sdl' CFLAGS_FEATURES='-DCONFIG_MENU -DCONFIG_VIDEO_CAPTURE' CFLAGS_SDL='`sdl2-config --cflags`' LDFLAGS_COMMON='-lm  -lz     -ldl -framework IOKit `sdl2-config --static-libs` ' LEVEL=1

========== darkplaces-sdl (release) ==========
/Library/Developer/CommandLineTools/usr/bin/make prepare BUILD_DIR=build-obj/release/darkplaces-sdl
mkdir -p build-obj/release/darkplaces-sdl
cp -f makefile.inc build-obj/release/darkplaces-sdl/
cp -f makefile build-obj/release/darkplaces-sdl/
/Library/Developer/CommandLineTools/usr/bin/make -C build-obj/release/darkplaces-sdl darkplaces-sdl \
		DP_MAKE_TARGET=macosx \
		CFLAGS='  -MMD   -Wall -Winline -Werror=c++-compat -Wwrite-strings -Wshadow -Wold-style-definition -Wstrict-prototypes -Wsign-compare -Wdeclaration-after-statement -Wmissing-prototypes -DLINK_TO_ZLIB  -DUSEXMP  `sdl2-config --cflags` -D_FILE_OFFSET_BITS=64 -D__KERNEL_STRICT_NAMES -I../../../ -DCONFIG_MENU -DCONFIG_VIDEO_CAPTURE   -O3 -fno-strict-aliasing -fno-math-errno -fno-rounding-math -fno-signaling-nans -fno-trapping-math'\
		LDFLAGS='-O3 -fno-strict-aliasing -fno-math-errno -fno-rounding-math -fno-signaling-nans -fno-trapping-math -DSVNREVISION=`{ test -d .svn && svnversion; } || { test -d .git && git describe --always; } || echo -` -DBUILDTYPE=release -lm  -lz     -ldl -framework IOKit `sdl2-config --static-libs` ' LEVEL=2
cc -MMD   -Wall -Winline -Werror=c++-compat -Wwrite-strings -Wshadow -Wold-style-definition -Wstrict-prototypes -Wsign-compare -Wdeclaration-after-statement -Wmissing-prototypes -DLINK_TO_ZLIB  -DUSEXMP  `sdl2-config --cflags` -D_FILE_OFFSET_BITS=64 -D__KERNEL_STRICT_NAMES -I../../../ -DCONFIG_MENU -DCONFIG_VIDEO_CAPTURE   -O3 -fno-strict-aliasing -fno-math-errno -fno-rounding-math -fno-signaling-nans -fno-trapping-math -c ../../../vid_sdl.c -o vid_sdl.o
clang: warning: optimization flag '-fno-rounding-math' is not supported [-Wignored-optimization-argument]
clang: warning: optimization flag '-fno-signaling-nans' is not supported [-Wignored-optimization-argument]
../../../vid_sdl.c:43:11: error: implicit declaration of function 'IOMainPort' is invalid in C99 [-Werror,-Wimplicit-function-declaration]
        status = IOMainPort(MACH_PORT_NULL, &masterport);
                 ^
../../../vid_sdl.c:395:9: warning: 'IOHIDGetAccelerationWithKey' is deprecated: first deprecated in macOS 10.12 [-Wdeprecated-declarations]
                                        if(IOHIDGetAccelerationWithKey(mouseDev, CFSTR(kIOHIDMouseAccelerationType), &originalMouseS...
                                           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/IOKit.framework/Headers/hidsystem/IOHIDLib.h:95:1: note: 
      'IOHIDGetAccelerationWithKey' has been explicitly marked deprecated here
IOHIDGetAccelerationWithKey( io_connect_t handle, CFStringRef key, double * acceleration ) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0...
^
../../../vid_sdl.c:398:10: warning: 'IOHIDSetAccelerationWithKey' is deprecated: first deprecated in macOS 10.12 [-Wdeprecated-declarations]
                                                if(IOHIDSetAccelerationWithKey(mouseDev, CFSTR(kIOHIDMouseAccelerationType), -1.0) !...
                                                   ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/IOKit.framework/Headers/hidsystem/IOHIDLib.h:98:1: note: 
      'IOHIDSetAccelerationWithKey' has been explicitly marked deprecated here
IOHIDSetAccelerationWithKey( io_connect_t handle, CFStringRef key, double acceleration ) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, ...
^
../../../vid_sdl.c:428:9: warning: 'IOHIDSetAccelerationWithKey' is deprecated: first deprecated in macOS 10.12 [-Wdeprecated-declarations]
                                        if(IOHIDSetAccelerationWithKey(mouseDev, CFSTR(kIOHIDMouseAccelerationType), originalMouseSp...
                                           ^
/Library/Developer/CommandLineTools/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/IOKit.framework/Headers/hidsystem/IOHIDLib.h:98:1: note: 
      'IOHIDSetAccelerationWithKey' has been explicitly marked deprecated here
IOHIDSetAccelerationWithKey( io_connect_t handle, CFStringRef key, double acceleration ) __OSX_AVAILABLE_BUT_DEPRECATED(__MAC_10_0, ...
^
3 warnings and 1 error generated.
make[3]: *** [vid_sdl.o] Error 1
make[2]: *** [bin-release] Error 2
make[1]: *** [sdl-release] Error 2
make: *** [release] Error 2
╭─ ~/Desktop/build/darkplaces master   

i get this why would this be?

**Comment by Cloudwalk9** [comment]
Hey. When you can, `git pull` and retest. I've pushed 6bb6d96 to fix this.

**Comment by bones-was-here** [comment]
Several people seem to have been able to compile successfully on mac OS so it should be working currently.
