### ISSUE TITLE
Invalid comparison in cl_collision

### ISSUE THREAD

**Issue by mattreecebentley** [DarkPlacesEngine/darkplaces#55]
../../../cl_collision.c:981:22: warning: the comparison will always evaluate as 'true' for the address of 'frameblend' will never be NULL [-Waddress]
  981 |                 if ((&touch->priv.server->frameblend[0] && (touch->priv.server->frameblend[0].lerp != 1.0 || touch->priv.server->frameblend[0].subframe != 0)) || touch->priv.server->skeleton.relativetransforms)

What are the semantics of the first argument meant to be here?

**Comment by bones-was-here** [comment]
Looks like a broken and/or no longer relevant check to prevent null ptr deref, but that code block only runs when the CSQC world has spawned and some entities were found in the box, so we don't need it.
