### ISSUE TITLE
Incorrect if guarding in r_shadow

### ISSUE THREAD

**Issue by mattreecebentley** [DarkPlacesEngine/darkplaces#56]
../../../r_shadow.c:513:93: note: ...this statement, but the latter is misleadingly indented as if it were guarded by the 'if'

	if (r_shadow_bouncegrid_state.blurpixels[0]) Mem_Free(r_shadow_bouncegrid_state.blurpixels[0]); r_shadow_bouncegrid_state.blurpixels[0] = NULL;

There are dozens and dozens of these.
They have no effect because the second operation has no effect if the statement wasn't true. It may even be the more performant way of doing things, as the if statement may resolve to a faster operation with only one callable function.
However the second operations should be put on secondary lines for clarity, or the entire line replaced with:
	if (r_shadow_bouncegrid_state.blurpixels[0])
	{
		Mem_Free(r_shadow_bouncegrid_state.blurpixels[0]);
		r_shadow_bouncegrid_state.blurpixels[0] = NULL;
        }

**Comment by Shpoike** [comment]
its easier to convert that first semi-colon into a comma, keeping it compact on a single brace-less line may help readability (at least if there's multiple things getting freed, each on their own single line).

**Comment by bones-was-here** [comment]
I believe all the GCC 11 warns are fixed including this one by 6c43af5f0fbb35910c50d82ac6c0b0e26bb55012, I didn't get around to pushing those commits until recently.
