### ISSUE TITLE
Lighting bug when using Quake 1 remastered files from steam

### ISSUE THREAD

**Issue by theangrygrunt** [DarkPlacesEngine/darkplaces#59]
Playing around in darkplaces when I spotted this lighting bug on the second level of q1 (E1M2):

Non full lighting:
![dp20221104012431-00](https://user-images.githubusercontent.com/102942008/199928398-6d928e8c-2fda-4299-b0fd-f8232464cc1f.jpg)

Full lighting:

![dp20221104012411-00](https://user-images.githubusercontent.com/102942008/199928470-2d364a83-56d4-4719-b072-1c7c50799bb7.jpg)

The torch on the left is much brighter than the torch on the right is. No other torches have this bug on the map.

**Comment by hemebond** [comment]
That's working as expected. "full lighting" means using real-time lights. Unless you are using an rtlight pack (a separate download/install) then the lights will be generated based on the light entities in the level.

Those particular lights have a light level of 800, making them very bright. They are supposed to be spot-lights but that isn't supported on rtlights.

**Comment by theangrygrunt** [comment]
I'll download that then. Thanks!
