### ISSUE TITLE
+showscores outside of 'id1'

### ISSUE THREAD

**Issue by inf78** [DarkPlacesEngine/darkplaces#64]
I don't know if I'm doing something wrong, but '+showscores' isn't recognized and simply doesn't work anywhere outside of 'id1' base game.
E.g. If I load Quoth the standard way (-hipnotic -game quoth) and just do new game or load whatever Quoth map, pressing TAB will make DP complain: uknown command "+showscores".
But it happens with any other mod, SoA, DoE and Nehahra included. Strange.

Happens with the latest source from Nov 7, built on Mageia 8.

**Comment by inf78** [comment]
Trying to sort it out, it happens only if the -hipnotic, -rogue, -nehahra or -quoth are being used.
So if I run the mentioned Quoth with just -game quoth without the -hipnotic argument, +showscores works as it should.
Of course, the hipnotic hud isn't working in this case. Same for all the other cases.

So I also tried to impose the problem on some other mods that don't need any of those arguments for their hud or whatever working correctly and in this case, no problem, +showscores works.
So e.g. running Dopa with: -dopa -game dopa doesn't produce that problem.

**Comment by bones-was-here** [comment]
This was introduced in 46acef5491629d06eddb8e78ed01e50b175d2bd8 and breaks Nexuiz also.
