### ISSUE TITLE
[ft2] should we remove the `r_font_use_alphatexture`? It’s broken for a long time

### ISSUE THREAD

**Issue by NaitLee** [DarkPlacesEngine/darkplaces#69]
As the developer of #67 I had to deal with the `r_font_use_alphatexture` thing appeared in `ft2.c`. Workarounds like [this](https://github.com/NaitLee/darkplaces/blob/5bdbd5afd917568e854b530cd91b3855c1ab1db3/ft2.c#L1344) are considered (*before* testing and finding out this true issue) but didn’t rescue this fact —

After searching around I’ve found that [this commit in master](https://github.com/DarkPlacesEngine/darkplaces/commit/90a141660eecdb9cfe07bebeb7b07ac4f1ee448f) cause the configuration `r_font_use_alphatexture 1` to segfault the game, and probably also caused #66.

That commit is from 2018 and so far no relative hassles have been reported, that further explains that this “feature” isn’t used.

For the ease of code maintenance (and #67) it’s suggested to remove it just like #66.

Other notes:

- `r_font_use_alphatexture 1` **can** work in div0-stable branch for not including this commit, but it shows only black text (rather than white & shadowed). You can see it easily by launching xonotic 0.8.5 with this as parameter:  
  `$ ./xonotic-linux64-sdl +r_font_use_alphatexture 1`
- With the commit before that (`5a126af930cb0f3c66b3065218d939d4bbacb613`), the game can start with `r_font_use_alphatexture 1` but glyphs are all white squares, also considered broken
- You may `git checkout` to these branches/commits and compile to test all these out

**Comment by bones-was-here** [comment]
Probably it worked when implemented, but I expect the newer font features and more generic rendering paths aren't compatible.  For saving font memory in VRAM there's `r_font_compress` which still works.

**Comment by bones-was-here** [comment]
I removed the last bits f0f6982297b24bf60c35503f705a11d83a549cfe
