### ISSUE TITLE
“You have reached this menu due to missing or unlocatable content/data. You may consider adding -basedir /path/to/game to your launch commandline.”

### ISSUE THREAD

**Issue by rokejulianlockhart** [DarkPlacesEngine/darkplaces#70]
[“You have reached this menu due to missing or unlocatable content/data. You may consider adding -basedir /path/to/game to your launch commandline.” appears when I launch darkplaces](https://forums.gentoo.org/viewtopic-t-937108-start-0.html#:~:text=you%20have%20reached%20this%20menu%20due%20to%20missing%20or%20unlocatable%20content%2Fdata.%20you%20may%20consider%20adding%20-basedir%20%2Fpath%2Fto%2Fgame%20to%20your%20launch%20commandline).

~~What to do after this is not immediately obvious.~~

**Comment by kiwixz** [comment]
Problem is the working directory.  It should point to the folder where you installed the game.

Either start the game from its folder or pass it like suggested in the error.

**Comment by rokejulianlockhart** [comment]
Oh, I see. Apologies. That is rather obvious.

However, why is the binary unable to extract the location of itself and search for its basedir within that directory? Even a PowerShell script can do that.

**Comment by kiwixz** [comment]
I think you downloaded only the engine (darkplaces), you need also the assets (game code, maps, models etc) for the specific game you want to play.

**Comment by rokejulianlockhart** [comment]
@kiwixz, that's almost definitely it. Do you know where to acquire them?

**Comment by kiwixz** [comment]
Depends which game you want to play.  If it's the original quake you need to purchase it AFAIK, but you could also choose https://xonotic.org/ or any other compatible game.

**Comment by rokejulianlockhart** [comment]
I've just installed [Quake from Steam](https://steamcommunity.com/id/rokejulianlockhart/recommended/2310?snr=1_5_9__402) instead. Thanks though.
