### ISSUE TITLE
DarkPlaces from Xonotic 0.8.5 higher cpu/gpu use

### ISSUE THREAD

**Issue by Baker7** [DarkPlacesEngine/darkplaces#73]
DarkPlaces compiled from Xonotic 0.8.2 -  darkplaces-wgl.vcproj Debug 32
vs.
DarkPlaces compiled from Xonotic 0.8.5 - darkplaces-wgl.vcproj Debug 32

On a basically empty Q3 map I made that has no dynamic lights ... and with cl_maxfps set to 72.

The DarkPlaces compiled from 0.8.5 uses 40% cpu and my graphics card fan starts blowing within a minute and I expect that within another minute Windows thermal shutdown will happen.

The DarkPlaces compiled from 0.8.2 uses 24% cpu and is as cool as a cucumber

( and I have accidentally had it running in the background for hours and hours many times before and I can't remember the last time it caused the fan to start churning with my rather vanilla normal use settings).

**Comment by bones-was-here** [comment]
WGL is deprecated and basically unmaintained, and nobody builds div0-stable that way.  If you're doing any development and/or want the latest DP you should use master branch (the sources in 0.8.5 are div0-stable branch).  If not, you should use the xonotic.exe (SDL2) included in the zip (cross-compiled on linux by the official build system).

**Comment by Baker7** [comment]
I just wanted to say thank you for the reply.  I understand everything you said regarding versions and am aware the current DP is SDL2 only.

I am using the 0.8.2 for a few different reasons including I know the behavior.  At some point I will likely switch to the current version.

I have done quite a few user interface changes, should they ever interest you guys they are visually summed on this page (**visually**, for ease of seeing them).

ihttps://www.moddb.com/mods/zircon-engine/tutorials/visual-guide-to-engine-changes

Keep up the great work!

**Comment by bones-was-here** [comment]
Apart from any build issues, I'd need to know more about what you're doing exactly so as to reproduce the issue, it doesn't look like you're playing Xonotic :P

A CPU/GPU load increase for the same content implies FPS reduction when the hardware can't sustain the configured maxfps and ticrate, but in practise we see the opposite: 0.8.5 performs better than 0.8.2, especially when considering worst-case frametimes.

If DP recognises that it's window is minimised it doesn't render anything, but if it's running a server that will continue to use resources.

**Comment by Baker7** [comment]
My 2012 laptop has Intel Integrated and it is likely that since 0.8.5 is using OpenGL 3 some of the functions are run via software emulation, while 0.8.2 using OpenGL 2 it is run fully on the GPU.

Which would result in high cpu use, etc.

So that is more than likely why.
