### ISSUE TITLE
macOS build error

### ISSUE THREAD

**Issue by federicochiesa** [DarkPlacesEngine/darkplaces#79]
When I use ```make sdl-release``` I get the following error: error: too many arguments to function call, expected 2, have 3
                        VID_SetMouse(false, false, false); // ungrab first!
                        ~~~~~~~~~~~~               ^~~~~
I got the latest commit 1244b3a

**Comment by kiwixz** [comment]
Oops !  It looks like 2a97ec851bd607510e33148335fc61d51e7138cf forgot the macOS path.  Try to remove one of the `false`.

**Comment by jminor** [comment]
Removing one of the "false" worked for me. The line now reads:
`VID_SetMouse(false, false); // ungrab first!`

**Comment by bones-was-here** [comment]
mybad, most of that func is untested by me as most of it is workarounds for mac weirdness :P
