### ISSUE TITLE
Monster interpolation tied to step movetype

### ISSUE THREAD

**Issue by MarioSMB** [DarkPlacesEngine/darkplaces#82]
Interpolation for Quake-style monsters is hardcoded to the MOVETYPE_STEP movetype: https://github.com/DarkPlacesEngine/darkplaces/blob/master/sv_send.c#L580

**Comment by Baker7** [comment]
cvar_t sv_gameplayfix_monsterinterpolate = {CF_SERVER, "sv_gameplayfix_monsterinterpolate", "1", "Scrag interpolation.  Force interpolation via RENDER_STEP for all FL_MONSTER entities. [Zircon]"};

	if (PRVM_serveredictfloat(ent, movetype) == MOVETYPE_STEP)
		cs->sflags |= RENDER_STEP;
	else if (sv_gameplayfix_monsterinterpolate.integer && Have_Flag ((int)PRVM_serveredictfloat(ent, flags), FL_MONSTER_32))
		cs->sflags |= RENDER_STEP;

**Comment by MarioSMB** [comment]
Thanks for the info, it would be great to see that feature merged into DarkPlaces - indeed there are some cases (especially in mods) where non-step movetype monsters would greatly benefit from interpolation, appearing very choppy without it.
