### ISSUE TITLE
Missing items in levels

### ISSUE THREAD

**Issue by inf78** [DarkPlacesEngine/darkplaces#85]
I just recently tried some other maps in DP and in RC2 (old map from fat controller) there is a missing DBS along with its ammo box.
Also, there is a missing red armor in NEH1M5. I encountered this problem in some other map as well, but can't remember which one it was. I'm on Linux, running from latest source.

RC2:
![RC2-no-dbs](https://github.com/DarkPlacesEngine/darkplaces/assets/121169133/b7085a6c-1a2f-43fb-a464-f0b287d908a2)

NEH1M5:
![neh1m5-no-red-armor](https://github.com/DarkPlacesEngine/darkplaces/assets/121169133/7a030e9d-26e3-42b3-90b1-6b357446eb4a)

**Comment by inf78** [comment]
I tested some older DP Windows builds and I can confirm that this problem is present in both maps since the build from 1.3.2013, while build from 22.12.2012 doesn't have this issue.

**Comment by inf78** [comment]
Yeah, the third map where it happens is HIP2M5, just to the right from start there should be 2 boxes of nails in the secret on the right. Again, that build from 2012 is ok, the 2013 one has the problem.

**Comment by hemebond** [comment]
```
walkmonster in wall at: '672.0 -3232.0  81.0'
Bonus item fell out of level at '104.0 -1696.0  22.0'
Bonus item fell out of level at '136.0 -1712.0  22.0'
Bonus item fell out of level at '1040.0 -1064.0  46.0'
Bonus item fell out of level at '208.0 -368.0 -602.0'
```

**Comment by bones-was-here** [comment]
`sv_gameplayfix_droptofloorstartsolid` is a workaround and Quake didn't have anything like that.  Quake also didn't have `sv_gameplayfix_droptofloorstartsolid_nudgetocorrect`.  Having workarounds enabled by default leads to maps that rely on them, so personally I'd want to at least spam warns every time the workarounds are needed...

**Comment by inf78** [comment]
I also tried the `sv_gameplayfix_droptofloorstartsolid_nudgetocorrect`, but that doesn't help with those missing items.
Warning would surely be nice thing to have here. Quake didn't have those workarounds, but it also didn't need them. :D

**Comment by bones-was-here** [comment]
> By default it's 0, after changing to 1, it fixes all those 3 issues!

It's 1 by default in current sources, and in div0-stable... except in certain games.  Which game (argument or binary name) are you using?

**Comment by hemebond** [comment]
I don't know how inf78 is running it, but in my compiled version (darkplaces master branch):
```
sv_gameplayfix_droptofloorstartsolid is "0" ["0"] prevents items and monsters that start in a solid area from falling out of the level (makes droptofloor treat trace_startsolid as an acceptable outcome)
sv_gameplayfix_droptofloorstartsolid_nudgetocorrect is "0" ["0"] tries to nudge stuck items and monsters out of walls before droptofloor is performed
```

**Comment by bones-was-here** [comment]
This particular cvar's default is changed to 0 for specific supported games, but the "global" default is 1, which is used when running `darkplaces-sdl` with no args, or when using an unsupported binary name, or when using a supported binary name but passing the `-quake` argument, eg:
```
xonotic-linux64-sdl -quake
Game is DarkPlaces-Quake using base gamedir id1
```
It's also 1 when running nexuiz or steelstorm.

**Comment by hemebond** [comment]
> running darkplaces-sdl with no args

That's all I'm doing. Compiled it. Copied to `/usr/local/games/quake/`. Ran with `./darkplaces-sdl`. cvars are both 0.

**Comment by bones-was-here** [comment]
I guess it's getting changed in some .cfg file then...

**Comment by hemebond** [comment]
I removed my `~/.darkplaces/id1/` directory and still defaulted to `0`. I removed `/usr/local/games/quake/id1/` and while it failed to start (because the paks were missing) the defaults were `1`.

**Comment by hemebond** [comment]
> not convinced I should change that.

Why not? Everyone who doesn't use DarkPlaces gets it.

**Comment by inf78** [comment]
Thinking about it, I don't know how difficult it would be to implement, since I'm not really a coder, but would it be possible to do some form of a mapname detection regarding this gameplayfix?
So if E1M1 or any other of the id1 map is loaded, the fix default would be automatically reverted so it would be disabled for those maps. And only if user specifically enables it on startup through autoexec.cfg or other config file, it would remain enabled?

**Comment by hemebond** [comment]
> would it be possible to do some form of a mapname detection regarding this gameplayfix?

This also affects many community maps, like ad_swampy where you lose the grenade launcher. Monsters being stuck in the walls, and items falling out of the world, is one of the main reasons mappers recommend against DarkPlaces, and don’t even bother testing in it.

**Comment by inf78** [comment]
Yeah, it's a pity, because DP still just has some extra cool features. Ironically enough, I really prefer it's way of handling mouse input, it feels much more natural and not so nervous with high sensitivity settings, like all Fitz descendants e.g. And also getting around walls and edges doesn't feel so 'sticky'. Basically, even though I love some maps with RT world enabled (and I'm slowly trying to make Nehahra much more bearable with it), it's about the general playability that makes DP better than most for me.
And who needs Copper if one can just enable fallen zombie gibbing in the engine. ;)

**Comment by bones-was-here** [comment]
> Why not? Everyone who doesn't use DarkPlaces gets it.  

It looks to be disabled by default in FTEQW, wasn't implemented original GLQuake, and isn't implemented in Quakespasm 0.95.1.  Which engine(s) are you referring to?
LH disabled it deliberately in 34e819a626f6a7ff2ad190a8e7d42e38ca8cef0e "for better compatibility [with other engines] and avoiding gameplay changes".  

I've added the warns (which the other engines don't have) in a branch. DP is already quite spammy when loading buggy maps (as it should be IMO).

Behaviour changes based on map names would be a dodgy hack, that kind of thing doesn't belong in a game engine as it causes subtle compatibility issues with mods and custom maps, then later someone will create content that depends on it, becoming a headache for maintenance/debugging.  Xonotic mapinfo files allow cvars to be temporarily set on a per-map basis without hard-coding, which is probably the least bad way to implement something like that.

It's possible to add a QUAKE_GAMEPLAYFIX (or something to that effect) game and default cvar set, so you'd run `darkplaces-sdl -quake_gameplayfix` and it would enable all that stuff.

DP also supports loading .ent files directly, which makes it pretty easy to fix broken items on closed source maps.

**Comment by hemebond** [comment]
>  Which engine(s) are you referring to?

I meant everyone else gets the health pack.

![image](https://github.com/DarkPlacesEngine/darkplaces/assets/424218/a8792ad3-2459-47aa-9d0f-364eb487fe77)
![image](https://github.com/DarkPlacesEngine/darkplaces/assets/424218/d0009b57-df2d-45ce-ad2d-c8408936acd5)
![image](https://github.com/DarkPlacesEngine/darkplaces/assets/424218/4be5427b-06e9-4bc7-85d9-6e5a7f6be591)

**Comment by bones-was-here** [comment]
Oh wtf... in that case DP should have it too, without needing `sv_gameplayfix_droptofloorstartsolid 1`.  I'll attempt to debug it.

**Comment by bones-was-here** [comment]
The patches are in this branch if you want to test them https://gitlab.com/xonotic/darkplaces/-/merge_requests/144

It _should_ fix all these kinds of problems for all Quake maps... and spam warns for maps with broken stuff.

**Comment by hemebond** [comment]
Tested it on e1m1 and rc2 and the items that were missing are there now.

**Comment by inf78** [comment]
Same here. I also tested NEH1M5 and HIP2M5, fixes these too. Great!
