### ISSUE TITLE
r_fakelight 2 no longer works (missing in glsl shader text) cvar remains

### ISSUE THREAD

**Issue by Baker7** [DarkPlacesEngine/darkplaces#93]
r_fakelight 2 no longer works (missing in glsl shader text), the cvar remains.  So r_fakelight 2 does not work.

Discovered while reading through source code.

(Tried to report this at gitlab, after signing up it insists I must create a project and won't let me do anything until I do.  I had to choose "create project" or "join project" during registration there.  Just providing information why I am reporting this here instead of where I know the actual development is occuring.)

**Comment by hemebond** [comment]
@Baker7 Is this still an issue? I can't find "fakelight" mentioned anywhere in the codebase.

**Comment by hemebond** [comment]
Looks like it was removed in commit https://github.com/DarkPlacesEngine/darkplaces/commit/0ea8f691e05ea968bb8940942197fa627966ff99
